Repository DKU-STUDY/Algorithm, pull requests merged in 2020-07, with the labels that each got.

#221 lessons.lesson15.CaterpillarMethod.MinAbsSumOfTwo + CountDistinctSlices
  codility_training/lessons.lesson15.CaterpillarMethod.CountDistinctSlices/sjjyy.java
  codility_training/lessons.lesson15.CaterpillarMethod.MinAbsSumOfTwo/sjjyy.java
Labels: JAVA

#222 lessons.lesson16.GreedyAlgorithms.MaxNonOverLappingSegments + TieRopes
  codility_training/lessons.lesson16.GreedyAlgorithms.MaxNonOverLappingSegments/sjjyy.java
  codility_training/lessons.lesson16.GreedyAlgorithms.TieRopes/sjjyy.java
Labels: JAVA

#220 level03.네트워크
  programmers/난이도별/level03.네트워크/JeongShin.js
Labels: JavaScript

#228 level03.베스트앨범
  programmers/난이도별/level03.네트워크/JeongShin.js
  programmers/난이도별/level03.베스트앨범/JeongShin.js
Labels: JavaScript

#224 프로그래머스 난이도별 level.01 크레인 인형뽑기 수정 완료
  programmers/난이도별/level01.실패율/README.md
  programmers/난이도별/level01.크레인_인형뽑기_게임/dkdlelk99.py
Labels: Python

#229 0703 일일 커밋/ programmers level01.실패율
  programmers/난이도별/level01.실패율/dkdlelk99.py
Labels: Python

#227 lessons.lesson11.SieveofEratosthenes.CountNonDivisible
  codility_training/lessons.lesson11.SieveofEratosthenes.CountNonDivisible/eyabc.js
Labels: JavaScript

#230 부스트캠프 1차 코딩테스트
  programmers/부스트캠프/1.js
  programmers/부스트캠프/2.js
Labels: JavaScript

#232 level03.가장먼노드
  programmers/난이도별/level03.가장먼노드/JeongShin.js
Labels: JavaScript

#225 lessons.lesson17.DynamicProgramming.NumberSolitaire
  codility_training/lessons.lesson17.DynamicProgramming.NumberSolitaire/sjjyy.java
  programmers/난이도별/level.01하샤드_수/sjjyy.java
Labels: JAVA

#223 lessons.lesson07.StacksandQueues.Nesting
  codility_training/lessons.lesson06.Sorting.MaxProductOfThree/khw970421.js
  codility_training/lessons.lesson06.Sorting.Triangle/khw970421.js
  codility_training/lessons.lesson07.StacksandQueues.Nesting/eyabc.js
  codility_training/lessons.lesson07.StacksandQueues.Nesting/khw970421.js
  codility_training/lessons.lesson09.MaximumSliceProblem.MaxProfit/khw970421.js
Labels: JavaScript

#234 프로그래머스 level01.2016년
  programmers/난이도별/level01.2016년/sjjyy.java
  programmers/난이도별/level01/하샤드_수/README.md
  programmers/난이도별/level01/하샤드_수/dkdlelk99.py
  programmers/난이도별/level01/하샤드_수/sjjyy.java
Labels: JAVA

#235 lessson13.FibonacciNumbers.Fibfrog
  codility_training/lessons.lesson13.FibonacciNumbers.FibFrog/sAp00n.py
Labels: Python

#231 0705 일일 커밋 / 프로그래머스 level01.다트 게임
  programmers/난이도별/level01.다트_게임/README.md
  programmers/난이도별/level01.다트_게임/dkdlelk99.py
Labels: Python

#238 level03.예산 , 타일 장식물
  programmers/난이도별/level03.예산/JeongShin.js
  programmers/난이도별/level03.타일_장식물/JeongShin.js
Labels: JavaScript

#233 lessons.lesson11.SieveofEratosthenes.CountSemiprimes
  codility_training/lessons.lesson11.SieveofEratosthenes.CountSemiprimes/READMD.md
  codility_training/lessons.lesson11.SieveofEratosthenes.CountSemiprimes/eyabc.js
Labels: JavaScript

#237 0707 일일커밋 / 프로그래머스 level02.가장 큰 수
  programmers/난이도별/level02.가장_큰_수/README.md
  programmers/난이도별/level02.가장_큰_수/dkdlelk99.py
Labels: Python

#240 프로그래머스 level01.K번째수 + 수박수박수박수
  programmers/난이도별/level01.K번째수/sjjyy.java
  programmers/난이도별/level01/수박수박수박수/sjjyy.java
Labels: JAVA

#246 lessons.lesson12.EuclideanAlgorithm.CommonPrimeDivisors
  codility_training/lessons.lesson12.EuclideanAlgorithm.CommonPrimeDivisors/README.md
  codility_training/lessons.lesson12.EuclideanAlgorithm.CommonPrimeDivisors/eyabc.js
Labels: JavaScript

#247 level03.입국심사
  codility_training/lessons.lesson13.FibonacciNumbers.FibFrog/JeongShin.js
  codility_training/lessons.lesson15.CaterpillarMethod.CountDistinctSlices/JeongShin.js
  codility_training/lessons.lesson17.DynamicProgramming.NumberSolitaire/JeongShin.js
  codility_training/lessons.lesson99.FutureTraining.ArrayInversionCount/JeongShin.js
  codility_training/lessons.lesson99.FutureTraining.TreeHeight/JeongShin.js
  programmers/난이도별/level03.이중우선순위큐/JeongShin.js
  programmers/난이도별/level03.입국심사/JeongShin.js
Labels: JavaScript

#244 level01.K번째수
  programmers/난이도별/level01.K번째수/rockmiin.py
  programmers/부스트캠프/boost1.py
  programmers/부스트캠프/boost2.py
Labels: Python

#245 프로그래머스 level01 x만큼 간격이 있는 n개의 숫자 + 비밀지도
  programmers/난이도별/level01.x만큼_간격이_있는_n개의_숫자/sjjyy.java
  programmers/난이도별/level01.비밀지도/README.md
  programmers/난이도별/level01.비밀지도/dkdlelk99.py
  programmers/난이도별/level01.비밀지도/sjjyy.java
  programmers/난이도별/level01.수박수박수박수/README.md
  programmers/난이도별/level01.수박수박수박수/dkdlelk99.py
  programmers/난이도별/level01.수박수박수박수/sjjyy.java
  programmers/난이도별/level01.하샤드_수/README.md
  programmers/난이도별/level01.하샤드_수/dkdlelk99.py
  programmers/난이도별/level01.하샤드_수/sjjyy.java
Labels: JAVA

#249 level01.2016년
  programmers/난이도별/level01.2016년/rockmiin.py
  programmers/난이도별/level01.[1차]_비밀지도/rockmiin.py
  programmers/난이도별/level01.체육복/rockmiin.py
Labels: Python

#242 0709 일일커밋 / 프로그래머스 level02 기능개발
  programmers/난이도별/level02.기능개발/README.md
  programmers/난이도별/level02.기능개발/dkdlelk99.py
Labels: Python

#251 level03.여행경로
  programmers/난이도별/level03.여행경로/JeongShin.js
  programmers/난이도별/level03.이중우선순위큐/JeongShin.js
Labels: JavaScript

#255 level01.두 정수 사이의 합 & 2016년
  programmers/난이도별/level01.2016년/HyeonJeong.py
  programmers/난이도별/level01.두_정수_사이의_합/HyeonJeong.c
Labels: C, Python

#239 lesson13.CountSemiPrime 재도전...
  codility_training/lessons.lesson11.SieveofEratosthenes.CountSemiprimes/sAp00n.py
  codility_training/lessons.lesson13.FibonacciNumbers.Ladder/sAp00n.py
Labels: Python

#250 프로그래머스 level01.같은_숫자는_싫어
  programmers/난이도별/level01.같은_숫자는_싫어/sjjyy.java
Labels: JAVA

#253 level01.두 정수 사이의 합
  .DS_Store
  programmers/.DS_Store
  programmers/난이도별/.DS_Store
  programmers/난이도별/level01.가운데_글자_가져오기/README.md
  programmers/난이도별/level01.가운데_글자_가져오기/rockmiin.py
  programmers/난이도별/level01.두_정수_사이의_합/rockmiin.py
  programmers/난이도별/level01.서울에서_김서방_찾기/rockmiin.py
Labels: Python

#256 level03.여행경로 👉 실패 ㅠㅠ
  codility_training/lessons.lesson13.FibonacciNumbers.FibFrog/JeongShin.js
  programmers/난이도별/level03.여행경로/JeongShin.js
  programmers/난이도별/level03.이중우선순위큐/JeongShin.js
Labels: JavaScript

#258 level01.2016년
  programmers/난이도별/level01.2016년/s2uyeoii.c
Labels: C++

#262 프로그래머스 level01 나누어 떨어지는 숫자 배열 + 다트 게임
  programmers/난이도별/level01.나누어_떨어지는_숫자_배열/sjjyy.java
  programmers/난이도별/level01.다트_게임/sjjyy.java
  programmers/난이도별/level01.두_정수_사이의_합/sjjyy.java
Labels: JAVA

#263 level03.여행경로
  programmers/난이도별/level03.여행경로/JeongShin.js
Labels: JavaScript

#259 level01.평균_구하기
  programmers/난이도별/level01.평균_구하기/HyeonJeong.java
Labels: JAVA

#265 프로그래머스.level01.모의고사
  programmers/난이도별/level01.나누어_떨어지는_숫자_배열/sjjyy.java
  programmers/난이도별/level01.모의고사/sjjyy.java
Labels: JAVA

#260 lessons.lesson01.Iterations.BinaryGap
  codility_training/lessons.lesson01.Iterations.BinaryGap/sangmandu.py
  codility_training/lessons.lesson02.Arrays.CyclicRotation/sangmandu.py
Labels: Python

#266 level01.약수의 합
  programmers/난이도별/level01.약수의_합/HyeonJeong.py
Labels: Python

#267 프로그래머스.level01.문자열_내_p와_y의_개수
  programmers/난이도별/level01.모의고사/sjjyy.java
  programmers/난이도별/level01.문자열_내_p와_y의_개수/sjjyy.java
Labels: JAVA

#268 level03.2xn타일링
  programmers/난이도별/level01.모의고사/JeongShin.js
  programmers/난이도별/level03.2xn타일링/JeongShin.js
  programmers/난이도별/level03.디스크_컨트롤러/JeongShin.js
Labels: JavaScript

#252 0710 일일 커밋 / 프로그래머스 level02 쇠막대기
  programmers/난이도별/level02.쇠막대기/README.md
  programmers/난이도별/level02.쇠막대기/dkdlelk99.py
Labels: Python

#275 Jaewon0702_level.02_위장.py
  programmers/난이도별/level02.위장/Jaewon0702_위장.py
Labels: Python

#272 프로그래머스.level01.문자열_다루기_기본
  programmers/난이도별/level01.문자열_다루기_기본/sjjyy.java
Labels: JAVA

#269 level01:모의고사
  programmers/난이도별/level01.같은_숫자는_싫어/rockmiin.py
  programmers/난이도별/level01.나누어_떨어지는_숫자_배열/rockmiin.py
  programmers/난이도별/level01.모의고사/rockmiin.py
Labels: Python

#274 level01.K번째수
  programmers/난이도별/level01.K번째수/HyeonJeong.py
Labels: Python

#273 level02.큰_수_만들기
  programmers/난이도별/level01.모의고사/JeongShin.js
  programmers/난이도별/level02.위장/JeongShin.js
  programmers/난이도별/level02.큰_수_만들기/JeongShin.js
Labels: JavaScript

#278 프로그래머스.level01.문자열을_정수로_바꾸기
  programmers/난이도별/level01.문자열을_정수로_바꾸기/sjjyy.java
Labels: JAVA

#276 easyearn77_1
  programmers/난이도별/level01.2016년/easyearn77.cpp
Labels: C++

#279 Jaewon0702_정렬_level.01_k번째 수
  programmers/난이도별/level01.K번째수/Jaewon0702_k번째 수.py
  programmers/난이도별/level02.가장_큰_수/Jaewon0702_가장 큰 수.py
Labels: Python

#281 level03.디스크_컨트롤러
  programmers/난이도별/level02.큰_수_만들기/JeongShin.js
  programmers/난이도별/level03.디스크_컨트롤러/JeongShin.js
Labels: JavaScript

#280 level01.다트게임
  programmers/난이도별/level01.다트_게임/rockmiin.py
Labels: Python

#285 level02. 소수만들기(summer/winter coding (~2018)) 업로드
  programmers/난이도별/level02.소수 만들기/소수만들기_s2uyeoii.cpp
Labels: C++

#277 MinMaxDivision
  codility_training/lessons.lesson14.BinarySearchAlgorithm.MinMaxDivision/sAp00n.py
  codility_training/lessons.lesson14.BinarySearchAlgorithm.MinMaxDivision/sAp00n_pseudo.md
Labels: Python, 코드리뷰

#282 level01.완주하지못한선수
  programmers/난이도별/level01.완주하지_못한_선수/rockmiin.py
Labels: Python

#271 lessons.lesson03.TimeComplexity.FrogJmp/PermMissingElem/TapeEquilibrium
  codility_training/lessons.lesson02.Arrays.OddOccurrencesInArray/sangmandu.py
  codility_training/lessons.lesson03.TimeComplexity.FrogJmp/sangmandu.py
  codility_training/lessons.lesson03.TimeComplexity.PermMissingElem/sangmandu.py
  codility_training/lessons.lesson03.TimeComplexity.TapeEquilibrium/sangmandu.py
Labels: Python

#283 level03.종이접기
  programmers/난이도별/level01.완주하지_못한_선수/JeongShin.js
  programmers/난이도별/level03.가장_긴_팰린드롬/JeongShin.js
  programmers/난이도별/level03.종이접기/JeongShin.js
Labels: JavaScript

#284 level01.수박수박수박수 & 문자열_다루기_기본(완료)
  programmers/난이도별/level01.문자열_다루기_기본/HyeonJeong.py
  programmers/난이도별/level01/수박수박수박수/HyeonJeong.py
Labels: Python

#290 level02.탑
  programmers/난이도별/level02.탑/rockmiin.py
Labels: Python

#288 프로그래머스.level01.문자열_내_마음대로_정렬하기+문자열_내림차순으로_배치하기
  programmers/난이도별/level01.문자열_내_마음대로_정렬하기/sjjyy.java
  programmers/난이도별/level01.문자열_내림차순으로_배치하기/sjjyy.java
Labels: JAVA

#291 level03.줄_서는_방법 & level03.하노이의_탑
  programmers/난이도별/level02.큰_수_만들기/JeongShin.js
  programmers/난이도별/level03.줄_서는_방법/JeongShin.js
  programmers/난이도별/level03.하노이의_탑/JeongShin.js
Labels: JavaScript

#289 lessons.lesson04.CountingElements.FrogRiverOne / MaxCounters
  codility_training/lessons.lesson03.TimeComplexity.PermMissingElem/sangmandu.py
  codility_training/lessons.lesson03.TimeComplexity.TapeEquilibrium/sangmandu.py
  codility_training/lessons.lesson04.CountingElements.FrogRiverOne/sangmandu.py
  codility_training/lessons.lesson04.CountingElements.MaxCounters/sangmandu.py
  codility_training/lessons.lesson04.CountingElements.MissingInteger/sangmandu.py
  codility_training/lessons.lesson04.CountingElements.PermCheck/sangmandu.py
Labels: Python

#286 Jaewon0702_위장, k번째 수,H-index
  programmers/난이도별/level01.K번째수/Jaewon0702.py
  programmers/난이도별/level02.H-Index/Jaewon0702
  programmers/난이도별/level02.H-Index/Jaewon0702.py
  programmers/난이도별/level02.위장/Jaewon0702.py
Labels: Python

#293 프로그래머스.level01.서울에서_김서방_찾기+소수찾기
  programmers/난이도별/level01.서울에서_김서방_찾기/sjjyy.java
  programmers/난이도별/level01.소수찾기/sjjyy.java
Labels: JAVA

#295 Jaewon0702_H-Index
  programmers/난이도별/level02.H-Index/Jaewon0702
Labels: Python

#294 level03.거스름돈
  programmers/난이도별/level03.거스름돈/JeongShin.js
Labels: JavaScript

#299 level01.소수찾기 &
  .DS_Store
  programmers/.DS_Store
  programmers/난이도별/.DS_Store
  programmers/난이도별/level01.소수찾기/rockmiin.py
Labels: Python

#298 level03.거스름돈
  programmers/난이도별/level03.거스름돈/JeongShin.js
Labels: JavaScript

#297 lessons.lesson05.PrefixSum.GenomicRangeQuery/ CountDiv/
  codility_training/lessons.lesson05.PrefixSum.GenomicRangeQuery/sangmandu.py
  codility_training/lessons.lesson05.PrefixSums.CountDiv/sangmandu.py
Labels: Python

#296 level01.이상한_문자_만들기(완료)
  programmers/난이도별/level01.문자열_다루기_기본/HyeonJeong.py
  programmers/난이도별/level01.이상한_문자_만들기/HyeonJeong.py
Labels: Python

#301 level01.정수_제곱근_판별
  programmers/난이도별/level01.정수_제곱근_판별/HyeonJeong.py
Labels: Python

#302 lesson15.CaterpillarMethod.AbsDistinct
  codility_training/lessons.lesson15.CaterpillarMethod.AbsDistinct/sAp00n.py
Labels: Python, 코드리뷰

#306 level03.야근지수, level03.저울
  programmers/난이도별/level03.야근지수/JeongShin.js
  programmers/난이도별/level03.저울/JeongShin.js
Labels: JavaScript

#309 level01.나누어_떨어지는_숫자_배열
  programmers/난이도별/level01.나누어_떨어지는_숫자_배열/HyeonJeong.py
Labels: Python

#310 level03.멀리뛰기, level03.최고의집합
  programmers/난이도별/level03.멀리뛰기/JeongShin.js
  programmers/난이도별/level03.최고의_집합/JeongShin.js
Labels: JavaScript

#304 0723 일일커밋 / 프로그래머스 level02 타겟 넘버
  programmers/난이도별/level02.타겟_넘버/README.md
  programmers/난이도별/level02.타겟_넘버/dkdlelk99.py
Labels: Python

#308 Jaewon0702 다리를 지나는 트럭
  programmers/난이도별/level02.다리를_지나는_트럭/Jaewon0702.py
Labels: Python

#312 Jaewon0702_level02.탑
  programmers/난이도별/level02.탑/Jaewon0702.py
Labels: Python

#311 level01.하샤드_수 & 직사각형_별찍기
  programmers/난이도별/level01.직사각혁_별찍기/HyeonJeong.py
  programmers/난이도별/level01/하샤드_수/HyeonJeong.py
Labels: Python

#313 level02.타겟_넘버
  programmers/난이도별/level02.타겟_넘버/JeongShin.js
Labels: JavaScript

#315 level01.하샤드_수
  programmers/난이도별/level01.최대공약수와_최소공배수/rockmiin.py
  programmers/난이도별/level01.평균_구하기/rockmiin.py
  programmers/난이도별/level01.하샤드_수/rockmiin.py
Labels: Python

#316 level01.콜라츠_추측
  programmers/난이도별/level01.콜라츠_추측/HyeonJeong.py
Labels: Python

#320 Jaewon0702 level 02. 기능개발
  programmers/난이도별/level02.기능개발/Jaewon0702.py
Labels: Python

#318 est2020.07 solution1
  codility_training/Est2020.07/1.js
Labels: JavaScript

#323 level02.큰_수_만들기.cpp
  programmers/난이도별/level02.큰_수_만들기/s2uyeoii.cpp
Labels: C++

#317 level02.H-index
  programmers/난이도별/level02.H-Index/rockmiin.py
Labels: Python

#322 level03.순위
  programmers/난이도별/level03.순위/JeongShin.js
Labels: JavaScript

#307 lessons.lesson05.PrefixSums.MinAvgTwoSlice / PassingCars / lesson06.Sorting.Distinct / MaxProductOfThree
  codility_training/lessons.lesson05.PrefixSums.MinAvgTwoSlice/sangmandu.py
  codility_training/lessons.lesson05.PrefixSums.PassingCars/sangmandu.py
  codility_training/lessons.lesson06.Sorting.Distinct/sangmandu.py
  codility_training/lessons.lesson06.Sorting.MaxProductOfThree/sangmandu.py
  codility_training/lessons.lesson06.Sorting.NumberOfDiscIntersections/sangmandu.py
  codility_training/lessons.lesson06.Sorting.Triangle/sangmandu.py
  codility_training/lessons.lesson07.StackandQueues.StoneWall/sangmandu.py
  codility_training/lessons.lesson07.StacksandQueues.Brackets/sangmandu.py
  codility_training/lessons.lesson07.StacksandQueues.Fish/sangmandu.py
  codility_training/lessons.lesson07.StacksandQueues.Nesting/sangmandu.py
Labels: Python

#325 level01.제일_작은_수_제거하기
  programmers/난이도별/level01.제일_작은_수_제거하기/HyeonJeong.py
Labels: Python

#328 level03.방문 길이
  programmers/난이도별/level03.방문_길이/JeongShin.js
Labels: JavaScript

#331 BOJ.2740.행렬곱셈
  BOJ/2740.행렬곱셈/sAp00n.py
Labels: Python

#332 level04.징검다리
  programmers/난이도별/level04.징검다리/JeongShin.js
Labels: JavaScript

#329 level01.제일 작은 수 제거하기
  programmers/난이도별/level01.제일_작은_수_제거하기/rockmiin.py
  programmers/난이도별/level01.짝수와_홀수/rockmiin.py
Labels: Python

#324 Revert "level02.큰_수_만들기.cpp "
  programmers/난이도별/level02.큰_수_만들기/s2uyeoii.cpp
Labels: C++
