Repository DKU-STUDY/Algorithm, pull requests merged in 2020-09, with the labels that each got.

#413 level03.불법 사용자 풀이
  programmers/난이도별/level03.불량_사용자/JeongShin.java
Labels: JAVA

#419 level02.위장
  programmers/난이도별/level02.위장/HyeonJeong.py
  programmers/난이도별/level02/기능개발/README.md
Labels: Python

#415 lessons.lesson09.MaximumSliceProblem.MaxSliceSum/MaxProfit
  codility_training/lessons.lesson09.MaximumSliceProblem.MaxProfit/sangmandu.py
  codility_training/lessons.lesson09.MaximumSliceProblem.MaxSliceSum/sangmandu.py
Labels: Python

#421 Jaewon0702 level 01. 핸드폰 번호 가리기
  programmers/난이도별/level01.핸드폰_번호_가리기/Jaewon0702.py
Labels: Python

#420 level02.다음 큰 숫자
  programmers/난이도별/level02.다음_큰_숫자/rockmiin.py
  programmers/난이도별/level02.다음_큰_숫자/rockmiin_다음큰숫자.py
Labels: Python

#418 프로그래머스 LV2 기능개발
  programmers/난이도별/level02.기능개발/dkdlelk99_v2.py
Labels: Python

#423 Jaewon0702 level 01. 정수 제곱근 판별
  programmers/난이도별/level01.정수_제곱근_판별/Jaewon0702.py
Labels: Python

#424 level02.올바른_괄호
  programmers/난이도별/level02/올바른_괄호/HyeonJeong.py
  programmers/난이도별/level02/올바른_괄호/README.md
Labels: Python

#425 Jaewon0702 Programmers level 01. 제일 작은 수 제거하기
  programmers/난이도별/level01.제일_작은_수_제거하기/Jaewon0702.py
Labels: Python

#426 level02.최솟값만들기
  programmers/난이도별/level02.최솟값만들기/rockmiin.py
Labels: Python

#428 Jaewon0702 level 01. 자릿수 더하기
  programmers/난이도별/level01.자릿수_더하기/Jaewon0702.py
Labels: Python

#429 level02.올바른_괄호 2
  programmers/난이도별/level02/올바른_괄호/HyeonJeong.py
Labels: Python

#430 level01.핸드폰 번호 가리기.cpp
  programmers/난이도별/level01.핸드폰_번호_가리기/s2uyeoii.cpp
  programmers/난이도별/level01.핸드폰_번호_가리기/s2uyeoii_c.cpp
Labels: C, C++

#431 Jaewon0702 level 01. 자연수 뒤집어 배열로 만들기(3개의 풀이)
  programmers/난이도별/level01.자연수_뒤집어_배열로_만들기/Jaewon0702.py
Labels: Python

#434 Jaewon0702 level 01. 최대공약수와 최소공배수
  programmers/난이도별/level01.최대공약수와_최소공배수/Jaewon0702.py
Labels: Python

#432 level02.숫자의 표현
  programmers/난이도별/level02/H-Index/HyeonJeong.py
  programmers/난이도별/level02/H-Index/README.md
  programmers/난이도별/level02/숫자의_표현/HyeonJeong.py
  programmers/난이도별/level02/숫자의_표현/README.md
Labels: Python

#437 level02.H-Index
  programmers/난이도별/level02/H-Index/HyeonJeong.py
  programmers/난이도별/level02/H-Index/README.md
Labels: Python

#433 level02.행렬의곱셈
  programmers/난이도별/level02.행렬의곱셈/rockmiin.py
Labels: Python

#436 s2uyeoii.cpp
  programmers/난이도별/level01.하샤드_수/s2uyeoii.cpp
Labels: C

#385 프로그래머스.level01
  programmers/난이도별/level01.가운데_글자_가져오기/sjjyy.java
  programmers/난이도별/level01.직사각혁_별찍기/sjjyy.java
  programmers/난이도별/level01.짝수와_홀수/sjjyy.java
  programmers/난이도별/level01.체육복/sjjyy.java
  programmers/난이도별/level01.최대공약수와_최소공배수/sjjyy.java
  programmers/난이도별/level01.콜라츠_추측/sjjyy.java
  programmers/난이도별/level01.크레인_인형뽑기_게임/sjjyy.java
  programmers/난이도별/level01.평균_구하기/sjjyy.java
  programmers/난이도별/level01.핸드폰_번호_가리기/sjjyy.java
  programmers/난이도별/level01.행렬의_덧셈/sjjyy.java
Labels: JAVA

#427 LeetCode/Array/Combination_Sum_II/JeongShin.js 풀이
  LeetCode/Array/Combination_Sum/JeongShin.js
  LeetCode/Array/Combination_Sum_II/JeongShin.js
  LeetCode/Array/Longest_Common_Subsequence/JeongShin.js
  LeetCode/Array/Permutations/JeongShin.js
  LeetCode/Array/Permutations_II/JeongShin.js
  LeetCode/DFS/PathSum_II/JeongShin.js
  programmers/난이도별/level02/올바른_괄호/JeongShin.js
Labels: JavaScript

#438 lessons.lesson10.PrimeAndCompositeNumbers.CountFactors/Flags
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.CountFactors/sangmandu.py
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.Flags/sangmandu.py
Labels: Python

#441 Create s2uyeoii.cpp
  programmers/난이도별/level01.수박수박수박수/s2uyeoii.cpp
Labels: C

#443 프로그래머스.level02.124_나라의_숫자
  programmers/난이도별/level02.124_나라의_숫자/sjjyy.java
Labels: JAVA

#444 lessons.lesson10.PrimeAndCompositeNumbers.MinPerimeterRectangle/Peaks
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.MinPerimeterRectangle/sangmandu.py
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.Peaks/sangmandu.py
Labels: Python

#445 BOJ 1245.농장관리
  BOJ/1068.트리/sAp00n.py
  BOJ/1068.트리/sAp00n_BFS.py
  BOJ/1245.농장관리/input_data.md
  BOJ/1245.농장관리/sAp00n.py
  BOJ/solved.ac_class/Class03/1003.피보나치 함수/sAp00n.py
  BOJ/solved.ac_class/Class03/1012.유기농 배추/sAp00n.py
Labels: Python, 코드리뷰

#447 level01.콜라츠_추측
  programmers/난이도별/level01.콜라츠_추측/s2uyeoii.cpp
Labels: C

#448 level02.최대값과 최솟값
  programmers/난이도별/level02/최대값과_최솟값/HyeonJeong.py
Labels: Python

#451 Jaewon0702 level 01. 정수 내림차순으로 배치하기
  README.md
  programmers/난이도별/level01.정수_내림차순으로_배치하기/정수_내림순으로_배치하기.py
Labels: Python

#450 Solved BOJ 1260 DFS와 BFS
  BOJ/1260.DFS와 BFS/input_data.md
  BOJ/1260.DFS와 BFS/sAp00n.py
Labels: Python, 코드리뷰

#442 (8) 카카오 - 크레인 인형뽑기 게임, 키패드 누르기, 비밀지도, 실패율, 다트게임, 문자열압축, 괄호변환, 튜플
  JSTestModule.js
  programmers/카카오/괄호변환/eyabc.js
  programmers/카카오/괄호변환/test.json
  programmers/카카오/다트게임/eyabc.js
  programmers/카카오/다트게임/test.json
  programmers/카카오/문자열압축/eyabc.js
  programmers/카카오/문자열압축/test.json
  programmers/카카오/비밀지도/eyabc.js
  programmers/카카오/비밀지도/test.json
  programmers/카카오/실패율/eyabc.js
  programmers/카카오/실패율/test.json
  programmers/카카오/크레인_인형뽑기_게임/eyabc.js
  programmers/카카오/키패드_누르기/eyabc.js
  programmers/카카오/키패드_누르기/test.json
  programmers/카카오/튜플/eyabc.js
  programmers/카카오/튜플/test.json
Labels: JavaScript

#446 프로그래머스.난이도별.level02.H-Index
  programmers/난이도별/level02.H-Index/sjjyy.java
Labels: JAVA

#452 level01.자연수뒤집어배열만들기 & 이상한 문자 만들기
  programmers/난이도별/level01.이상한_문자_만들기/s2uyeoii.cpp
  programmers/난이도별/level01.자연수_뒤집어_배열로_만들기/s2uyeoii.cpp
Labels: C

#456 프로그래머스.level02.가장_큰_수
  programmers/난이도별/level02.가장_큰_수/sjjyy.java
Labels: JAVA

#457 BOJ 바이러스, 트리의 부모찾기 ++ Python 유저분들을 위한 약간의 영업자료?
  BOJ/.swp
  BOJ/11725.트리의 부모 찾기/input_data.md
  BOJ/11725.트리의 부모 찾기/sAp00n.py
  BOJ/2606.바이러스/sAp00n.py
  Tips/BOJ 영업자료.md
Labels: Python, 코드리뷰

#453 LeetCode Number of Islands & lengthOfLongestSubstring 풀이
  LeetCode/DFS/Number_of_Islands/JeongShin.js
  LeetCode/DFS/Target_Sum/JeongShin.js
  LeetCode/Sliding_Window/Longest_Substring_Without_Repeating_Characters/JeongShin.js
  programmers/카카오_2020_블라인드채용_코딩테스트/01.문자열압축/JeongShin.js
Labels: JavaScript

#458 프로그래머스.level02.구명보트
  programmers/난이도별/level02.구명보트/README.md
  programmers/난이도별/level02.구명보트/sjjyy.java
Labels: JAVA

#459 Jaewon0702 level 01. x만큼 간격 있는 n개의 숫자
  programmers/난이도별/level01.x만큼_간격이_있는_n개의_숫자/x만큼_간격_있는_n개의_숫자.py
Labels: Python

#461 프로그래머스 LV2 큰 수 만들기
  programmers/난이도별/level02.큰_수_만들기/README.md
  programmers/난이도별/level02.큰_수_만들기/dkdlelk99.py
Labels: Python

#466 level01.크래인 인형뽑기 게임
  programmers/난이도별/level01.크레인_인형뽑기_게임/HyeonJeong.py
Labels: Python

#435 9/7 포켓몬
  programmers/난이도별/level02.폰켓몬/khw.js
  programmers/알고리즘(khw970421)/README.md
  programmers/알고리즘(khw970421)/level2/폰켓몬.js
Labels: JavaScript

#463 LeetCode/Array/Two_sum
  LeetCode/Array/TwoSum/eyabc.js
Labels: JavaScript

#464 LeetCode/BFS/Word_Ladder 풀이
  LeetCode/BFS/Word_Ladder/JeongShin.js
  LeetCode/BFS/Word_Ladder_II/JeongShin.js
  LeetCode/Binary_Search/Search-in-Rotated-Sorted-Array/JeongShin.js
Labels: JavaScript

#467 1325.효율적인 해킹
  BOJ/1325.효율적인 해킹/효율적인해킹_1325.py
Labels: Python

#471 1181.단어정렬(미완)
  BOJ/1181.단어 정렬/rockmiin.py
Labels: Python

#472 level01.실패율& level02.다음_큰_숫자
  programmers/난이도별/level01.실패율/HyeonJeong.py
  programmers/난이도별/level02/다음_큰_숫자/HyeonJeong.py
  programmers/난이도별/level02/다음_큰_숫자/README.md
Labels: Python

#473 BOJ 1074 Z
  BOJ/1199.오일러 회로/sAp00n.py
  BOJ/solved.ac_class/Class03/1074.Z/sAp00n.md
  BOJ/solved.ac_class/Class03/1074.Z/sAp00n.py
Labels: Python, 코드리뷰

#474 leetcode/dp/coin change 풀이
  LeetCode/Dynamic_Programming/Coin_Change/JeongShin.js
  programmers/난이도별/level04.올바른_괄호의_갯수/JeongShin.js
Labels: JavaScript

#477 프로그래머스.level01.JadenCase_문자열_만들기
  programmers/난이도별/level02/JadenCase_문자열_만들기/HyeonJeong.py
  programmers/난이도별/level02/JadenCase_문자열_만들기/README.md
Labels: Python

#480 leetcode/greedy/Split_a_String_in_Balanced_Strings
  LeetCode/Greedy/ Split_a_String_in_Balanced_Strings/eyabc.js
Labels: JavaScript

#468 [level01]완주하지 못한선수
  programmers/난이도별/level.01.두개_뽑아서_더하기/khw970421.js
  programmers/난이도별/level01.2016년/khw970421.js
  programmers/난이도별/level01.K번째수/khw970421.js
  programmers/난이도별/level01.나누어_떨어지는_숫자_배열/khw970421.js
  programmers/난이도별/level01.문자열_내림차순으로_배치하기/khw970421.js
  programmers/난이도별/level01.완주하지_못한_선수/khw970421.js
  programmers/난이도별/level01.체육복/khw970421.js
  programmers/알고리즘(khw970421)/README.md
  programmers/알고리즘(khw970421)/level2/폰켓몬.js
Labels: JavaScript, 도움요청, 프로그래머스

#481 [level02]기능개발, 스킬트리
  programmers/난이도별/level02/기능개발/eyabc.js
  programmers/난이도별/level02/스킬트리/eyabc.js
Labels: EASY, JavaScript, 프로그래머스

#476 [level02]기능개발
  programmers/난이도별/level02.기능개발/sjjyy.java
Labels: JAVA, 프로그래머스

#479 [union_find]surrounded regions
  LeetCode/Union_Find/Surrounded_Regions/JeongShin.js
Labels: JavaScript, leetcode

#483 [level02]스킬트리
  programmers/난이도별/level02/스킬트리/HyeonJeong.py
  programmers/난이도별/level02/스킬트리/README.md
Labels: EASY, Python, 프로그래머스

#484 [UnionFind]Surrounded Regions
  LeetCode/Union_Find/Surrounded_Regions/eyabc.js
Labels: JavaScript, NOMAL, leetcode
