Repository DKU-STUDY/Algorithm, pull requests merged in 2020-05, with the labels that each got.

#115 일일 pr입니다
  codility_training/lessons.lesson08.Leader.Dominator/JeongShin.js
Labels: JavaScript

#118 일일 pr입니다
  codility_training/lessons.lessons08.Leader.EquiLeader/JeongShin.js
Labels: JavaScript

#116 lesson07.StacksandQueues.Nesting
  codility_training/lessons.lesson07.StacksandQueues.Nesting/README.md
  codility_training/lessons.lesson07.StacksandQueues.Nesting/eyabc.js
Labels: JavaScript

#121 lessons.lesson07.StackandQueues.StoneWall
  codility_training/lessons.lesson07.StackandQueues.StoneWall/README.md
  codility_training/lessons.lesson07.StackandQueues.StoneWall/eyabc.js
Labels: JavaScript

#117 lessons.lesson01.Iterations.BinaryGap
  codility_training/lessons.lesson01.Iterations.BinaryGap/khw970421.js
  codility_training/lessons.lesson02.Arrays.CyclicRotation/khw970421.js
  codility_training/lessons.lesson03.TimeComplexity.TapeEquilibrium/khw970421.js
Labels: JavaScript

#124 lessons.lesson07.StackandQueues.StoneWall
  codility_training/lessons.lesson07.StackandQueues.StoneWall/sjjyy.java
Labels: JAVA

#123 lessons.lesson08.Leader.Dominator
  codility_training/lessons.lesson08.Leader.Dominator/README.md
  codility_training/lessons.lesson08.Leader.Dominator/eyabc.js
Labels: JavaScript

#126 pr입니다. 풀다 모르겠어서 인터넷 참고하여 공부하였습니다
  codility_training/lessons.lesson09.MaximumSliceProblem.MaxDoubleSliceSum/JeongShin.js
Labels: JavaScript

#129 lessons.lesson07.StackandQueues.Nesting
  codility_training/lessons.lesson07.StacksandQueues.Nesting/sjjyy.java
Labels: JAVA

#130 lessons.lesson02.Arrays.CyclicRotation/khw970421.js
  codility_training/lessons.lesson01.Iterations.BinaryGap/khw970421.js
  codility_training/lessons.lesson02.Arrays.CyclicRotation/khw970421.js
  codility_training/lessons.lesson03.TimeComplexity.FrogJmp/khw970421.js
Labels: JavaScript

#133 lessons.lessons08.Leader.EquiLeader
  codility_training/lessons.lessons08.Leader.EquiLeader/eyabc.js
Labels: JavaScript

#127 sAp00n 2020.05.19 daily PR
  codility_training/lessons.lesson07.StacksandQueues.Fish/sAp00n.py
  codility_training/lessons.lesson09.MaximumSliceProblem.MaxSliceSum/README.md
  codility_training/lessons.lesson09.MaximumSliceProblem.MaxSliceSum/sAp00n.py
Labels: Python

#128 0519 일일 커밋입니다
  programmers/난이도별/level01.x만큼_간격이_있는_n개의_숫자/README.md
  programmers/난이도별/level01.x만큼_간격이_있는_n개의_숫자/dkdlelk99.py
  programmers/난이도별/level01.직사각혁_별찍기/README.md
  programmers/난이도별/level01.직사각혁_별찍기/dkdlelk99.py
  programmers/난이도별/level01.최대공약수와_최소공배수/README.md
  programmers/난이도별/level01.최대공약수와_최소공배수/dkdlelk99.py
Labels: Python

#136 일일 pr입니다. 지난번꺼 수정한거도 없는데 왜 뜨는지 잘 모르겠네요 ..
  codility_training/lessons.lesson09.MaximumSliceProblem.MaxDoubleSliceSum/JeongShin.js
  codility_training/lessons.lesson09.MaximumSliceProblem.MaxSliceSum/JeongShin.js
Labels: JavaScript

#137 0520 일일커밋
  programmers/난이도별/level01.이상한_문자_만들기/README.md
  programmers/난이도별/level01.이상한_문자_만들기/dkdlelk99.py
Labels: Python

#138 lesson09.MaximumSliceProblem.MaxDoubleSliceSum / MaxProfit
  codility_training/lessons.lesson08.Leader.EquiLeader/JeongShin.js
  codility_training/lessons.lesson08.Leader.EquiLeader/README.md
  codility_training/lessons.lesson08.Leader.EquiLeader/eyabc.js
  codility_training/lessons.lesson08.Leader.EquiLeader/junilhwang.js
  codility_training/lessons.lesson08.Leader.EquiLeader/sAp00n.py
  codility_training/lessons.lesson08.Leader.EquiLeader/test.json
  codility_training/lessons.lesson09.MaximumSliceProblem.MaxDoubleSliceSum/README.md
  codility_training/lessons.lesson09.MaximumSliceProblem.MaxDoubleSliceSum/eyabc-practice.js
  codility_training/lessons.lesson09.MaximumSliceProblem.MaxDoubleSliceSum/eyabc.js
  codility_training/lessons.lesson09.MaximumSliceProblem.MaxProfit/eyabc.js
Labels: JavaScript

#141 lessons.lesson07.StacksandQueues.Fish
  codility_training/lessons.lesson07.StacksandQueues.Fish/sjjyy.java
Labels: JAVA

#132 programmers/난이도별/level01/이상한_문자_만들기
  programmers/난이도별/level01.이상한_문자_만들기/README.md
  programmers/난이도별/level01.이상한_문자_만들기/pul8219.java
  programmers/썸머코딩_2020/01.아름다운연도/pul8219.java
Labels: JAVA

#144 lessons.lesson09.MaximumSliceProblem.MaxSliceSum
  codility_training/lessons.lesson09.MaximumSliceProblem.MaxSliceSum/eyabc.js
Labels: JavaScript

#145 일일 pr 입니다
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.Peaks/JeongShin.js
Labels: JavaScript

#147 lesson10.PrimeAndCompositeNumbers.CountFactors
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.CountFactors/PrimeAndCompositeNumber-practice.js
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.CountFactors/README.md
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.CountFactors/eyabc.js
Labels: JavaScript

#150 Codlity.Lesson08.Dominator / java 풀이 완료
  codility_training/lessons.lesson08.Leader.Dominator/JunilHwang.java
Labels: JAVA

#140 lessons.lesson04.CountingElements.MaxCounters,PermCheck/khw970421
  codility_training/lessons.lesson04.CountingElements.MaxCounters/khw970421.js
  codility_training/lessons.lesson04.CountingElements.PermCheck/khw970421.js
Labels: JavaScript

#135 sAp00n 05 25 daily PR
  codility_training/lessons.lesson07.StacksandQueues.Fish/sAp00n.py
  codility_training/lessons.lesson09.MaximumSliceProblem.MaxDoubleSliceSum/sAp00n.py
  codility_training/lessons.lesson09.MaximumSliceProblem.MaxSliceSum/README.md
  codility_training/lessons.lesson09.MaximumSliceProblem.MaxSliceSum/sAp00n.py
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.CountFactors/sAp00n.py
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.Flags/sAp00n.py
Labels: Python

#151 0525 일일커밋입니다~
  programmers/난이도별/level01.예산/README.md
  programmers/난이도별/level01.예산/dkdlelk99.py
Labels: Python

#149 lessons.lesson08.Leader.Dominator
  codility_training/lessons.lesson08.Leader.Dominator/sjjyy.java
Labels: JAVA

#152 lessons.lesson08.Leader.EquiLeader
  codility_training/lessons.lesson08.Leader.EquiLeader/sjjyy.java
Labels: JAVA

#154 0526 일일 커밋입니다
  programmers/난이도별/level02.탑/README.md
  programmers/난이도별/level02.탑/dkdlelk99.py
Labels: Python

#155 lessons.lesson09.MaximumSliceProblem.MaxProfit
  codility_training/lessons.lesson09.MaximumSliceProblem.MaxProfit/sjjyy.java
Labels: JAVA

#156 05.27 daliyPR
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.Flags/Flag.md
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.Flags/sAp00n.py
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.MinPerimeterRectangle/sAp00n.py
Labels: Python

#157 lessons.lesson10.PrimeAndCompositeNumbers.Flags
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.Flags/eyabc.js
Labels: JavaScript

#159 일일 pr 입니다 두번째 문제는 어려워서 인터넷 보고 풀이 하였습니다 ㅠ
  codility_training/lessons.lesson12.EuclideanAlgorithm.ChocolatesByNumbers/JeongShin.js
  codility_training/lessons.lesson12.EuclideanAlgorithm.CommonPrimeDivisors/JeongShin.js
Labels: JavaScript

#160 lessons.lesson09.MaximumSliceProblem.MaxSliceSum
  codility_training/lessons.lesson09.MaximumSliceProblem.MaxProfit/README.md
  codility_training/lessons.lesson09.MaximumSliceProblem.MaxSliceSum/sjjyy.java
Labels: JAVA

#158 sAp00n 05.28 dailyPR
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.Peaks/sAp00n.py
Labels: Python

#163 lessons.lesson10.PrimeAndCompositeNumbers.CountFactors
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.CountFactors/sjjyy.java
Labels: JAVA

#166 lessons.lesson03.TimeComplexity.PermMissingElem
  codility_training/lessons.lesson03.TimeComplexity.PermMissingElem/pul8219.java
  programmers/난이도별/level01.이상한_문자_만들기/pul8219.java
Labels: JAVA

#161 Update dkdlelk99.py
  programmers/난이도별/level02.전화번호_목록/README.md
  programmers/난이도별/level02.전화번호_목록/dkdlelk99.py
  programmers/난이도별/level02.탑/dkdlelk99.py
Labels: Python
