Repository DKU-STUDY/Algorithm, pull requests merged in 2020-08, with the labels that each got.

#330 Jaewon0702 level02. 프린터
  programmers/난이도별/level02.프린터/Jaewon0702.py
Labels: Python

#327 0729 일일커밋 / 프로그래머스 레벨2 124 나라의 숫자
  programmers/난이도별/level02.124_나라의_숫자/README.md
  programmers/난이도별/level02.124_나라의_숫자/dkdlelk99.py
Labels: Python

#334 Jaewon0702 level02. 주식가격
  programmers/난이도별/level02.주식가격/Jaewon0702.py
  programmers/난이도별/level02.주식가격/README.md
Labels: Python

#337 level02.주식가격 & level03.정수삼각형
  programmers/난이도별/level02.주식가격/rockmiin.py
  programmers/난이도별/level03.정수삼각형/rockmiin.py
Labels: Python

#336 level03.불량 사용자
  programmers/난이도별/level03.불량_사용자/JeongShin.js
Labels: JavaScript

#335 level01.핸드폰_번호_가리기
  programmers/난이도별/level01.핸드폰_번호_가리기/HyeonJeong.py
Labels: Python

#339 level02.피보나치 수
  programmers/난이도별/level02.피보나치_수/rockmiin.py
Labels: Python

#340 level03.징검다리_건너기
  programmers/난이도별/level03.징검다리_건너기/JeongShin.js
Labels: JavaScript

#343 level01.x만큼_간격이_있는_n개의_숫자
  programmers/난이도별/level01.x만큼_간격이_있는_n개의_숫자/HyeonJeong.py
Labels: Python

#342 프로그래머스.level01.시저_암호
  programmers/난이도별/level01.시저_암호/sjjyy.java
  programmers/난이도별/level01.약수의_합/sjjyy.java
Labels: JAVA

#345 level01.문자열내림차순으로배치하기
  programmers/난이도별/level01.문자열_내림차순으로_배치하기/rockmiin.py
Labels: Python

#346 프로그래머스.level01.예산
  programmers/난이도별/level01.예산/sjjyy.java
Labels: JAVA

#344 level01.서울에서_김서방_찾기
  programmers/난이도별/level01.서울에서_김서방_찾기/HyeonJeong.java
  programmers/난이도별/level01.서울에서_김서방_찾기/HyeonJeong.py
  programmers/난이도별/level01.정수_내림차순으로_배치하기/HyeonJeong.py
Labels: JAVA, Python

#350 level04.가사검색
  programmers/난이도별/level04.가사_검색/JeongShin.js
Labels: JavaScript

#349 프로그래머스.level01.완주하지_못한_선수
  programmers/난이도별/level01.완주하지_못한_선수/sjjyy.java
Labels: JAVA

#347 Jaewon0702 level 02. 더 맵게, level 01. 모의고사
  programmers/난이도별/level01.모의고사/Jaewon0702 .py
  programmers/난이도별/level02.더 맵게/Jaewon0702.py
  programmers/난이도별/level02.더 맵게/README.md
Labels: Python

#348 level01.정수_내림차순으로_배치하기
  programmers/난이도별/level01.서울에서_김서방_찾기/HyeonJeong.java
  programmers/난이도별/level01.정수_내림차순으로_배치하기/HyeonJeong.py
Labels: Python

#333 solved.ac Class01
  BOJ/solved.ac_class/Class01/10818. 최소, 최대/sAp00n.py
  BOJ/solved.ac_class/Class01/10869.사칙연산/sAp00n.py
  BOJ/solved.ac_class/Class01/10950.A + B - 3/sAp00n.py
  BOJ/solved.ac_class/Class01/10951.A + B - 4/sAp00n.py
  BOJ/solved.ac_class/Class01/10952.A + B - 5/sAp00n.py
  BOJ/solved.ac_class/Class01/11654.아스키 코드/sAp00n.py
  BOJ/solved.ac_class/Class01/11720.숫자의 합/sAp00n.py
  BOJ/solved.ac_class/Class01/1330.두 수 비교하기/sAp00n.py
  BOJ/solved.ac_class/Class01/2438.별 찍기 - 1/sAp00n.py
  BOJ/solved.ac_class/Class01/2562.최댓값/sAp00n.py
  BOJ/solved.ac_class/Class01/2675.문자열 반복/sAp00n.py
  BOJ/solved.ac_class/Class01/2739.구구단/sAp00n.py
  BOJ/solved.ac_class/Class01/2920.음계/sAp00n.py
  BOJ/solved.ac_class/Class01/8958.OX퀴즈/sAp00n.py
Labels: Python

#355 level01.같은_숫자는_싫어
  programmers/난이도별/level01.같은_숫자는_싫어/HyeonJeong.py
Labels: Python

#353 level04.호텔_방_배정
  programmers/난이도별/level02.타겟_넘버/JeongShin.js
  programmers/난이도별/level04.호텔_방_배정/JeongShin.js
Labels: JavaScript

#352 Jaewon0702 level 02. 소수 찾기
  programmers/난이도별/level02.소수_찾기/Jaewon0702.py
Labels: Python

#351 프로그래머스.level01.이상한_문자_만들기
  programmers/난이도별/level01.이상한_문자_만들기/sjjyy.java
Labels: JAVA

#359 level04.지형이동
  programmers/난이도별/level04.지형_이동/JeongShin.js
Labels: JavaScript

#358 level01.소수찾기(미완료) & 문자열 내 p와 y의 개수
  programmers/난이도별/level01.문자열_내_p와_y의_개수/HyeonJeong.py
  programmers/난이도별/level01.소수찾기/HyeonJeong.py
Labels: Python

#360 level03.2*n타일링
  programmers/난이도별/level03.2xn타일링/rockmiin.py
Labels: Python

#356 프로그래머스.level01.자릿수_더하기
  codility_training/lessons.lesson04.CountingElements.MissingInteger/pul8219.java
  codility_training/lessons/lesson08/Leader/EquiLeader/JeongShin.js
  codility_training/lessons/lesson08/Leader/EquiLeader/README.md
  codility_training/lessons/lesson08/Leader/EquiLeader/eyabc.js
  codility_training/lessons/lesson08/Leader/EquiLeader/junilhwang.js
  codility_training/lessons/lesson08/Leader/EquiLeader/sAp00n.py
  codility_training/lessons/lesson08/Leader/EquiLeader/test.json
  programmers/난이도별/level01.자릿수_더하기/sjjyy.java
Labels: JAVA

#361 level01.문자열을_정수로_바꾸기
  programmers/난이도별/level01.문자열을_정수로_바꾸기/HyeonJeong.py
Labels: Python

#363 level04.단어_퍼즐
  programmers/난이도별/level04.단어_퍼즐/JeongShin.js
Labels: JavaScript

#357 Jaewon0702 level.02 카펫
  programmers/난이도별/level02.카펫/Jaewon0702.py
  programmers/난이도별/level02.카펫/README.md
Labels: Python

#362 프로그래머스.level01.자연수_뒤집어_배열로_만들기
  programmers/난이도별/level01.자연수_뒤집어_배열로_만들기/sjjyy.java
Labels: JAVA

#364 level01.체육복
  programmers/난이도별/level01.체육복/HyeonJeong.py
Labels: Python

#366 level01.콜라츠추측 & 예산
  programmers/난이도별/level01.예산/rockmiin_예산.py
  programmers/난이도별/level01.콜라츠_추측/rockmiin.py
Labels: Python

#369 LeetCode Unique_Paths, MinPathSum, TwoSum
  LeetCode/Array/TwoSum/JeongShin.js
  LeetCode/Dynamic_Programming/MinimumPathSum/JeongShin.js
  LeetCode/Dynamic_Programming/MinimumPathSum/ReadMe.md
  LeetCode/Dynamic_Programming/Unique_Paths/JeongShin.js
  LeetCode/Dynamic_Programming/Unique_Paths/ReadMe.md
  programmers/난이도별/level04.스티커_모으기/JeongShin.js
Labels: JavaScript

#370 프로그래머스.level01.정수_내림차순으로_배치하기 + 정수_제곱근_판별 + 제일_작은_수_제거하기
  programmers/난이도별/level01.정수_내림차순으로_배치하기/sjjyy.java
  programmers/난이도별/level01.정수_제곱근_판별/sjjyy.java
  programmers/난이도별/level01.제일_작은_수_제거하기/sjjyy.java
Labels: JAVA

#372 level04.스티커_모으기
  programmers/난이도별/level04.스티커_모으기/JeongShin.js
Labels: JavaScript

#371 level01.자릿수_더하기
  programmers/난이도별/level01.자릿수_더하기/HyeonJeong.py
Labels: Python

#365 Create s2uyeoii.cpp
  programmers/난이도별/level01.가운데_글자_가져오기/s2uyeoii.cpp
Labels: C++

#367 Jaewon0702 level 01.체육복
  programmers/난이도별/level01.체육복/Jaewon0702.py
Labels: Python

#374 level04.무지의 먹방 라이브
  programmers/난이도별/level04.무지의_먹방_라이브/JeongShin.js
Labels: JavaScript

#375 level01.문자열_내림차순으로_배치하기
  programmers/난이도별/level01.문자열_내림차순으로_배치하기/HyeonJeong.py
Labels: Python

#376 프로그래머스 Level02.H-index
  programmers/난이도별/level02.H-Index/README.md
  programmers/난이도별/level02.H-Index/dkdlelk99.py
Labels: Python

#378 LeetCode - Longest-Consecutive-Sequence
  LeetCode/Union_Find/Longest_Consecutive_Sequence/JeongShin.js
  programmers/난이도별/level04.무지의_먹방_라이브/JeongShin.js
Labels: JavaScript

#377 level01.모의고사
  programmers/난이도별/level01.모의고사/HyeonJeong.py
Labels: Python

#379 level01.문자열다루기기본 & p and y & 휴대폰 번호
  programmers/난이도별/level01.문자열_내_p와_y의_개수/rockmiin.py
  programmers/난이도별/level01.문자열_다루기_기본/rockmiin.py
  programmers/난이도별/level01.핸드폰_번호_가리기/rockmiin.py
Labels: Python

#380 level01.예산
  programmers/난이도별/level01.예산/HyeonJeong.py
Labels: Python

#382 level01.완주하지_못한_선수
  programmers/난이도별/level01.완주하지_못한_선수/HyeonJeong.py
Labels: Python, 코드리뷰

#383 LeetCode/Design_Add_and_Search_Words_Data_Structure 풀이 & level03.여행경로 복습 및 수정
  LeetCode/Trie/Design_Add_and_Search_Words_Data_Structure/JeongShin.js
  programmers/난이도별/level03.여행경로/JeongShin.js
Labels: JavaScript

#384 level01.시저_암호
  programmers/난이도별/level01.시저_암호/HyeonJeong.py
Labels: Python

#381 BOJ class02
  BOJ/solved.ac_class/Class02/10250.ACM호텔/sAp00n.py
  BOJ/solved.ac_class/Class02/10814.나이순 정렬/sAp00n.py
  BOJ/solved.ac_class/Class02/10816.숫자 카드2/sAp00n.py
  BOJ/solved.ac_class/Class02/10828.스택/sAp00n.py
  BOJ/solved.ac_class/Class02/10845.큐/sAp00n.py
  BOJ/solved.ac_class/Class02/10866.덱/sAp00n.py
  BOJ/solved.ac_class/Class02/11050. 이항계수/sAp00n.py
  BOJ/solved.ac_class/Class02/11650.좌표 정렬하기/sAp00n.py
  BOJ/solved.ac_class/Class02/11866.요세푸스 문제/sAp00n.py
  BOJ/solved.ac_class/Class02/1978.소수 찾기/sAp00n.py
  BOJ/solved.ac_class/Class02/2164.카드2/sAp00n.py
  BOJ/solved.ac_class/Class02/2609. 최대공약수와 최소공배수/sAp00n.py
  BOJ/solved.ac_class/Class02/2798.블랙잭/sAp00n.py
  BOJ/solved.ac_class/Class02/9023.괄호/sAp00n.py
  BOJ/solved.ac_class/Class03/1003.피보나치 함수/sAp00n.py
Labels: Python

#386 LeetCode/Backtracking/Letter_Combinations_of_a_Phone_Number/JeongShin.js
  LeetCode/Backtracking/Letter_Combinations_of_a_Phone_Number/JeongShin.js
  programmers/학점연계인턴십_2020_하반기/1.js
  programmers/학점연계인턴십_2020_하반기/2.js
  programmers/학점연계인턴십_2020_하반기/3.js
  programmers/학점연계인턴십_2020_하반기/4.js
  programmers/학점연계인턴십_2020_하반기/5.js
Labels: JavaScript

#387 level01.행렬의_덧셈
  programmers/난이도별/level01.행렬의_덧셈/HyeonJeong.py
Labels: Python

#391 LeetCode/Backtracking/Word_Search_II
  LeetCode/Backtracking/Word_Search_II/JeongShin.js
Labels: JavaScript

#395 socar 1번문제
  programmers/socar/1.js
Labels: JavaScript

#396 Jaewon0702 level 01. 두 정수 사이의 합
  programmers/난이도별/level01.두_정수_사이의_합/Jaewon0702 .py
Labels: Python

#400 LeetCode/Greedy/Jump_Game
  LeetCode/Greedy/Jump_Game/JeongShin.js
  programmers/난이도별/level02.가장_큰_수/JeongShin.js
  programmers/난이도별/level04.가사_검색/JeongShin.js
Labels: JavaScript

#399 level02.조이스틱
  programmers/난이도별/level02/조이스틱/HyeonJeong.py
  programmers/난이도별/level02/조이스틱/README.md
Labels: Python

#398 프로그래머스 level2 더 맵게
  programmers/난이도별/level02.더 맵게/dkdlelk99.py
Labels: Python

#401 level02.가장 큰 수 (미완)
  programmers/난이도별/level02.가장_큰_수/rockmiin_가장큰수.py
Labels: Python

#406 LeetCode/DP/Edit_Distance
  LeetCode/Dynamic_Programming/Edit_Distance/JeongShin.js
  programmers/난이도별/level04.지형_이동/JeongShin.js
Labels: JavaScript

#403 Jaewon0702 level 01. 나누어 떨어지는 숫자 배열, level 01. 문자열 내림차순으로 배치하기
  programmers/난이도별/level01.나누어_떨어지는_숫자_배열/Jaewon0702.py
  programmers/난이도별/level01.문자열_내림차순으로_배치하기/Jaewon0702.py
Labels: Python

#405 level02.최댓값과최솟값
  programmers/난이도별/level02.최댓값과_최솟값/rockmiin_최댓값과최솟값.py
Labels: Python

#407 level02.기능개발
  programmers/난이도별/level02/기능개발/HyeonJeong.py
  programmers/난이도별/level02/기능개발/README.md
Labels: Python

#408 LeetCode/Tree/Unique_Binary_Search_Tree
  LeetCode/Tree/Unique_Binary_Search_Trees/JeongShin.js
  programmers/난이도별/level04.징검다리/JeongShin.java
Labels: JavaScript

#404 프로그래머스 level2 주식가격
  programmers/난이도별/level02.주식가격/dkdlelk99.py
Labels: Python

#409 Jaewon0702 level 01. 문자열 정수로 바꾸기, level 01. 수박수박수박수박수박수
  programmers/난이도별/level01.문자열을_정수로_바꾸기/Jaewon0702.py
  programmers/난이도별/level01.수박수박수박수/Jaewon0702.py
Labels: Python

#410 level03.네트워크
  programmers/난이도별/level03.네트워크/rockmiin_네트워크.py
Labels: Python

#411 level04.징검다리 복습 & 릿코드 Combination Sum 풀이
  LeetCode/Array/Combination_Sum/JeongShin.js
  programmers/난이도별/level04.호텔_방_배정/JeongShin.java
Labels: JAVA, JavaScript

#412 level02.영어_끝말잇기
  programmers/난이도별/level02/영어_끝말잇기/HyeonJeong.py
  programmers/난이도별/level02/영어_끝말잇기/README.md
Labels: Python

#414 Jaewon0702 level 01. 평균 구하기(같은 문제, 다른 풀이), level 01. 짝수와 홀수
  programmers/난이도별/level01.짝수와_홀수/Jaewon0702.py
  programmers/난이도별/level01.평균_구하기/Jaewon0702.py
Labels: Python
