Repository DKU-STUDY/Algorithm, pull requests merged in 2020-11, with the labels that each got.

#546 level02.n개의 최소공배수
  programmers/난이도별/level02.N개의_최소공배수/rockmiin.py
Labels: NORMAL, Python

#548 [LeetCode] Longest Substring Without Repeating Characters
  LeetCode/String/Longest_Substring_Without_Repeating_Characters/HyeonJoeng.py
Labels: NORMAL, Python, leetcode, 문자열

#545 [level01] x만큼 간격이 있는 n개의 숫자, 다트 게임, 비밀지도, 실패율, 예산, 직사각형 별찍기, 콜라츠 추측, 평균 구하기, 하샤드 수, 핸드폰 번호 가리기, 행렬의 덧셈
  programmers/난이도별/level01.x만큼_간격이_있는_n개의_숫자/sangmandu.py
  programmers/난이도별/level01.다트_게임/sangmandu.py
  programmers/난이도별/level01.비밀지도/sangmandu.py
  programmers/난이도별/level01.실패율/sangmandu.py
  programmers/난이도별/level01.예산/sangmandu.py
  programmers/난이도별/level01.직사각혁_별찍기/sangmandu.py
  programmers/난이도별/level01.콜라츠_추측/sangmandu.py
  programmers/난이도별/level01.평균_구하기/sangmandu.py
  programmers/난이도별/level01.하샤드_수/sangmandu.py
  programmers/난이도별/level01.핸드폰_번호_가리기/sangmandu.py
  programmers/난이도별/level01.행렬의_덧셈/sangmandu.py
Labels: EASY, Python, 프로그래머스

#544 [level02] 큰 수 만들기
  programmers/난이도별/level02.큰_수_만들기/sjjyy.java
Labels: EASY, JAVA, 프로그래머스

#547 BOJ 11724. 연결요소의 개수 BOJ 11726. 2xn 타일링 BOJ 18870. 좌표 압축
  BOJ/solved.ac_class/Class03/11399. ATM/sAp00n.py
  BOJ/solved.ac_class/Class03/11723.집합/sAp00n.py
  BOJ/solved.ac_class/Class03/11724.연결 요소의 개수/sAp00n.py
  BOJ/solved.ac_class/Class03/11726.2xn 타일링/sAp00n.py
  BOJ/solved.ac_class/Class03/18870.좌표 압축/sAp00n.py
  BOJ/solved.ac_class/Class04/1149.RGB거리/sAp00n.py
Labels: BOJ, EASY, Python

#554 [Programmers]level01. 두개 뽑아서 더하기
  programmers/난이도별/level01.두 개 뽑아서 더하기/develop-sell.js
  programmers/난이도별/level01.문자열_내림차순으로_배치하기/develop-sell.js
Labels: JavaScript

#551 기능개발 문제풀이
  programmers/난이도별/level02.기능개발/6047198844.cpp
  programmers/난이도별/level02.스킬트리/6047198844.cpp
Labels: C++, EASY, 프로그래머스

#549 [Union Find] Friend Circles & [프로그래머스] 겨울 방학 인턴십
  LeetCode/Trie/Top_K_Frequent_Words/JeongShin.js
  LeetCode/Union_Find/Friend_Circles/JeongShin.js
  programmers/프로그래머스_챌린지/2020_하반기_겨울방학인턴십_코딩테스트/JeongShin1.js
  programmers/프로그래머스_챌린지/2020_하반기_겨울방학인턴십_코딩테스트/JeongShin3.js
Labels: JavaScript, NORMAL, leetcode

#552 [level02] 타겟 넘버
  programmers/난이도별/level02.타겟_넘버/sjjyy.java
Labels: EASY, JAVA, 프로그래머스

#550 [LeetCode] Search in Rotated Sorted Array
  LeetCode/Array/Search_in_Rotated_Sorted_Array/HyeonJoeng.py
Labels: EASY, Python, leetcode

#556 [DP] Word Break
  LeetCode/Dynamic_Programming/Word_Break/JeongShin.js
Labels: JavaScript, NORMAL, leetcode

#540 [level02]스킬트리
  programmers/난이도별/level02/스킬트리/dkdlelk99.py
Labels: NORMAL, Python, 프로그래머스

#555 프린터
  programmers/난이도별/level02.스킬트리/desktop.ini
  programmers/난이도별/level02.프린터/6047198844.cpp
Labels: C++, EASY, 프로그래머스

#558 프로그래머스 더맵게 & 조이스틱
  programmers/난이도별/level02.더 맵게/6047198844.cpp
  programmers/난이도별/level02.조이스틱/6047198844.cpp
Labels: C++, NORMAL, 프로그래머스

#542 level01[1차]비밀지도,x만큼_간격이_있는_n개의_숫자, level02 숫자의_표현, 올바른 괄호
  programmers/난이도별/level01.[1차]비밀지도/khw970421.js
  programmers/난이도별/level01.x만큼_간격이_있는_n개의_숫자/khw970421.js
  programmers/난이도별/level02.H-Index/khw970421.js
  programmers/난이도별/level02.숫자의_표현/khw970421.js
  programmers/난이도별/level02.올바른괄호/khw970421.js
Labels: JavaScript

#564 Level2 더괄호 변환 / 큰 수 만들기 / 전화번호 목록
  programmers/난이도별/level02.괄호_변환/6047198844.cpp
  programmers/난이도별/level02.전화번호_목록/6047198844.cpp
  programmers/난이도별/level02.큰_수_만들기/6047198844.cpp
Labels: C++, NORMAL, 프로그래머스

#553 BOJ 11057 오르막 수
  BOJ/11057.오르막 수/Munang.py
  BOJ/9465.스티커/Munang.py
Labels: BOJ, NORMAL, Python

#563 [프로그래머스 level2] 튜플
  programmers/난이도별/level02.튜플/JeongShin.js
Labels: JavaScript, 프로그래머스

#565 카펫/타겟넘버/위장
  programmers/난이도별/level02.위장/6047198844.cpp
  programmers/난이도별/level02.카펫/6047198844.cpp
  programmers/난이도별/level02.타겟_넘버/6047198844.cpp
Labels: C++, EASY, 프로그래머스

#575 [level02] 더 맵게, 큰 수 만들기
  programmers/난이도별/level01.다트_게임/eyabc.js
  programmers/난이도별/level01.비밀지도/eyabc.js
  programmers/난이도별/level01.실패율/eyabc.js
  programmers/난이도별/level01.크레인_인형뽑기_게임/eyabc.js
  programmers/난이도별/level01.키패드 누르기/eyabc.js
  programmers/난이도별/level02.H-Index/HyeonJeong.py
  programmers/난이도별/level02.H-Index/Jaewon0702.py
  programmers/난이도별/level02.H-Index/README.md
  programmers/난이도별/level02.H-Index/dkdlelk99.py
  programmers/난이도별/level02.H-Index/rockmiin.py
  programmers/난이도별/level02.H-Index/sjjyy.java
  programmers/난이도별/level02.JadenCase 문자열 만들기/HyeonJeong.py
  programmers/난이도별/level02.JadenCase 문자열 만들기/README.md
  programmers/난이도별/level02.괄호_변환/6047198844.cpp
  programmers/난이도별/level02.괄호변환/eyabc.js
  programmers/난이도별/level02.기능개발/HyeonJeong.py
  programmers/난이도별/level02.기능개발/eyabc.js
  programmers/난이도별/level02.다음_큰_숫자/HyeonJeong.py
  programmers/난이도별/level02.더 맵게/sangmandu.py
  programmers/난이도별/level02.문자열압축/eyabc.js
  programmers/난이도별/level02.숫자의_표현/HyeonJeong.py
  programmers/난이도별/level02.숫자의_표현/README.md
  programmers/난이도별/level02.스킬트리/6047198844.cpp
  programmers/난이도별/level02.스킬트리/HyeonJeong.py
  programmers/난이도별/level02.스킬트리/README.md
  programmers/난이도별/level02.스킬트리/dkdlelk99.py
  programmers/난이도별/level02.스킬트리/eyabc.js
  programmers/난이도별/level02.영어 끝말잇기/HyeonJeong.py
  programmers/난이도별/level02.영어 끝말잇기/junilhwang.py
  programmers/난이도별/level02.올바른괄호/HyeonJeong.py
  programmers/난이도별/level02.올바른괄호/JeongShin.js
  programmers/난이도별/level02.조이스틱/HyeonJeong.py
  programmers/난이도별/level02.최댓값과_최솟값/HyeonJeong.py
  programmers/난이도별/level02.큰_수_만들기/sangmandu.py
  programmers/난이도별/level02.튜플/eyabc.js
  programmers/난이도별/level02/기능개발/README.md
  programmers/난이도별/level02/다음_큰_숫자/README.md
  programmers/난이도별/level02/영어_끝말잇기/README.md
  programmers/난이도별/level02/올바른_괄호/README.md
  programmers/난이도별/level02/조이스틱/README.md
  programmers/알고리즘(khw970421)/README.md
  programmers/카카오/괄호변환/test.json
  programmers/카카오/다트게임/test.json
  programmers/카카오/문자열압축/test.json
  programmers/카카오/비밀지도/test.json
  programmers/카카오/실패율/test.json
  programmers/카카오/키패드_누르기/test.json
  programmers/카카오/튜플/test.json
Labels: NORMAL, Python, 프로그래머스

#574 [완전탐색] 소수찾기
  programmers/난이도별/level02.구명보트/6047198844.cpp
Labels: C++, EASY, 프로그래머스

#571 [level01] 크레인 인형뽑기 게임
  programmers/난이도별/level01.크레인_인형뽑기_게임/turquoiseluv.py
Labels: EASY, Python, 프로그래머스

#579 [level02]구명보트
  programmers/난이도별/level02.구명보트/6047198844.cpp
  programmers/난이도별/level02.소수_찾기/6047198844.cpp
Labels: C++, EASY, 프로그래머스

#573 BOJ 9465. 스티커
  BOJ/9465.스티커/Munang.py
Labels: BOJ, EASY, Python

#578 [Backtracking] Subsets
  LeetCode/Backtracking/Subsets/JeongShin.js
  LeetCode/Backtracking/Subsets_II/JeongShin.js
  LeetCode/String/Group_Anagrams/JeongShin.js
Labels: JavaScript, NORMAL, leetcode

#584 [level02] H-Index, 가장 큰 수
  programmers/난이도별/level01.비밀지도/khw970421.js
  programmers/난이도별/level01.비밀지도/rockmiin.py
  programmers/난이도별/level02.H-Index/sangmandu.py
  programmers/난이도별/level02.가장 큰 수/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#570 [LeetCode] 3Sum
  LeetCode/Array/3Sum/HyeonJeong.py
Labels: NORMAL, Python, leetcode, 도움요청

#583 [Level02] 가장 큰 정사각형의 길이
  programmers/난이도별/level02.가장_큰_정사각형_찾기/6047198844.cpp
Labels: C++, NORMAL, 프로그래머스

#585 [level02] 구명보트, 땅따먹기, 숫자의 표현, 최댓값과 최솟값, 최솟값 만들기
  programmers/난이도별/level02.구명보트/sangmandu.py
  programmers/난이도별/level02.땅따먹기/sangmandu.py
  programmers/난이도별/level02.숫자의 표현/sangmandu.py
  programmers/난이도별/level02.최댓값과 최솟값/sangmandu.py
  programmers/난이도별/level02.최솟값 만들기/rockmiin.py
  programmers/난이도별/level02.최솟값 만들기/sangmandu.py
  programmers/난이도별/level02.최솟값 만들기/sjjyy.java
  programmers/난이도별/level02.타켓 넘버/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#567 BOJ 1167.트리의 지름
  BOJ/9465.스티커/sAp00n.py
  BOJ/solved.ac_class/Class04/1176.트리의 지름/sAp00n.py
Labels: BOJ, NORMAL, Python

#586 [LeetCode] Reverse Integer
  LeetCode/Math/Reverse_Integer/HyeonJeong.py
Labels: EASY, Python, leetcode

#588 [level02] 쿼드압축 후 개수 세기
  programmers/난이도별/level02.쿼드압축 후 개수 세기/sangmandu.py
  programmers/난이도별/level02.타겟 넘버/sangmandu.py
Labels: NORMAL, Python, 도움요청, 프로그래머스

#580 [level01] 문자열 내 마음대로 정렬하기
  programmers/난이도별/level01.문자열_내_마음대로_정렬하기/turquoiseluv.py
Labels: EASY, Python, 프로그래머스

#559 [Programmers] 두 정수의 사이의 합 (add_from_1_to_number)
  programmers/난이도별/level01.두_정수_사이의_합/develop-sell.js
  programmers/난이도별/level01.수박수박수박수/develop-sell.js
Labels: JavaScript

#589 [Level02] 땅따먹기
  programmers/난이도별/level02.다리를_지나는_트럭/6047198844.cpp
  programmers/난이도별/level02.땅따먹기/6047198844.cpp
Labels: C++, EASY, 프로그래머스

#591 BOJ 1106.호텔
  BOJ/1106.호텔/sAp00n.py
Labels: BOJ, DP, EASY, Python

#592 [DFS] Course Schedule II 풀이
  LeetCode/DFS/Course_Schedule_II/JeongShin.js
Labels: JavaScript, leetcode

#590 [LeetCode] Add Binary & Sqrt(x)
  LeetCode/Math/Add_Binary/HyeonJeong.py
  LeetCode/Math/Sqrt(x)/HyeonJeong.py
Labels: EASY, leetcode

#597 [LeetCode] Length of Last Word
  LeetCode/String/Length_of_Last_Word/HyeonJeong.py
  LeetCode/String/ZigZag_Conversion/HyeonJeong.py
Labels: EASY, Python, leetcode

#601 [Level02]짝지어_제거하기
  programmers/난이도별/level02.짝지어_제거하기/6047198844.cpp
Labels: C++, EASY, 프로그래머스

#595 [Programmers Lv1.] 문자열 다루기 기본 basic_string_problem
  programmers/난이도별/level01.문자열 다루기 기본/develop-sell.js
Labels: JavaScript

#600 [Programmers Lv.1] 문자열_정수로_바꾸기 & 소수찾기 (primenumber_and_change_string_to_number_problem)
  programmers/난이도별/level01.문자열을_정수로_바꾸기/develop-sell.js
  programmers/난이도별/level01.소수찾기/develop-sell.js
Labels: JavaScript

#598 [level02] 뉴스 클러스터링, 영어 끝말잇기, 예상 대진표, 점프와 순간이동, 프렌즈4블록, [BOJ] 1106호텔
  BOJ/1106.호텔/sangmandu.py
  programmers/난이도별/level02.뉴스_클러스터링/sangmandu.py
  programmers/난이도별/level02.영어_끝말잇기/sangmandu.py
  programmers/난이도별/level02.예상_대진표/sangmandu.py
  programmers/난이도별/level02.점프와_순간이동/sangmandu.py
  programmers/난이도별/level02.프렌즈4블록/sangmandu.py
Labels: BOJ, NORMAL, Python, 프로그래머스

#604 [level02] N개의 최소공배수 / 가장 큰 수 / 다음 큰 숫자 / 멀쩡한 사각형 / 소수 만들기 / JadenCase 문자열 만들기
  programmers/난이도별/level02.N개의 최소공배수/6047198844.cpp
  programmers/난이도별/level02.가장_큰_수/6047198844.cpp
  programmers/난이도별/level02.다음_큰_숫자/6047198844.cpp
  programmers/난이도별/level02.멀쩡한_사각형/6047198844.cpp
  programmers/난이도별/level02.소수_만들기/6047198844.cpp
  programmers/난이도별/level02.짝지어_제거하기/6047198844.cpp
  programmers/난이도별/level02/JadenCase_문자열_만들기/6047198844.cpp
Labels: C++, NORMAL, 프로그래머스

#607 [level02]점프와 순간이동/영어 끝말잇기/예상 대진표/[1차]뉴스 클러스터링
  programmers/난이도별/level02.뉴스_클러스터링/6047198844.cpp
  programmers/난이도별/level02.영어_끝말잇기/6047198844.cpp
  programmers/난이도별/level02.예상_대진표/6047198844.cpp
  programmers/난이도별/level02.점프와_순간이동/6047198844.cpp
Labels: C++, EASY, 프로그래머스

#602 [Programmers Lv.1] 가운데_글자_가져오기 (middle_string_problem)
  programmers/난이도별/level01.가운데_글자_가져오기/develop-sell.js
Labels: JavaScript

#608 [level02] n진수 게임, 압축, 오픈채팅방, 캐시, 후보키
  programmers/난이도별/level02.n진수_게임/sangmandu.py
  programmers/난이도별/level02.압축/sangmandu.py
  programmers/난이도별/level02.오픈채팅방/sangmandu.py
  programmers/난이도별/level02.캐시/sangmandu.py
  programmers/난이도별/level02.후보키/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#610 [level02] 124 나라의 숫자
  programmers/난이도별/level02.124_나라의_숫자/turquoiseluv.py
Labels: NORMAL, Python, 프로그래머스

#606 [Lv.1] K번째 수 (k_number_problem)
  programmers/난이도별/level01.K번째수/develop-sell.js
Labels: JavaScript, 프로그래머스

#612 [level2]캐시
  programmers/난이도별/level02.캐시/6047198844.cpp
Labels: C++, NORMAL, 프로그래머스

#560 [level02] 튜플
  programmers/난이도별/level02.튜플/sjjyy.java
Labels: EASY, JAVA, 프로그래머스

#582 [Level 02] 최댓값과 최솟값
  programmers/난이도별/level02.최댓값과 최솟값/README.md
  programmers/난이도별/level02.최댓값과 최솟값/dkdlelk99.py
Labels: EASY, Python, 문자열, 프로그래머스

#611 ZigZag Conversion
  LeetCode/String/ZigZag_Conversion/HyeonJeong.py
  ㅅㄷㄴㅅ
Labels: Python, leetcode

#615 [Level02] 삼각달팽이
  programmers/난이도별/level02.삼각_달팽이/6047198844.cpp
Labels: C++, NORMAL, 프로그래머스

#605 BOJ 1932, 2565
  BOJ/1932.정수 삼각형/sAp00n.py
  BOJ/2526.전깃줄/sAp00n.py
Labels: BOJ, DP, EASY, Python

#618 [Level02]오픈채팅방
  programmers/난이도별/level02.오픈채팅방/6047198844.cpp
Labels: C++, EASY, 프로그래머스

#614 [Programmers Lv.1] 나누어 떨어지는 숫자 배열 (remain_zero_num_array_problem)
  programmers/난이도별/level01.나누어_떨어지는_숫자_배열/develop-sell.js
Labels: JavaScript

#613 [level02] 방금그곡, 파일명 정렬 [level03] 베스트앨범
  programmers/난이도별/level02. 방금그곡/sangmandu.py
  programmers/난이도별/level02.파일명_정렬/sangmandu.py
  programmers/난이도별/level03.베스트앨범/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#622 [level03] 2 x n 타일링, N으로 표현
  programmers/난이도별/level03.2xn타일링/sangmandu.py
  programmers/난이도별/level03.N으로_표현/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#621 [3차]_압축
  programmers/난이도별/level02.[3차]_압축/6047198844.cpp
Labels: C++, EASY, 프로그래머스

#623 [Tree] Path Sum III 풀이
  LeetCode/Tree/Path_Sum_III/JeongShin.js
Labels: JavaScript, NORMAL, leetcode

#624 [level03] 네트워크, 풍선 터트리기
  programmers/난이도별/level03.네트워크/sangmandu.py
  programmers/난이도별/level03.풍선_터트리기/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#619 BOJ 1629.곱셈, 1753.최단경로
  BOJ/solved.ac_class/Class04/1629.곱셈/sAp00n.py
  BOJ/solved.ac_class/Class04/1753.최단경로/sAp00n.py
Labels: BOJ, NORMAL, Python

#628 [Level02][1차]_프렌즈4블록
  programmers/난이도별/level02.[1차]_프렌즈4블록/6047198844.cpp
  programmers/난이도별/level03.2xn타일링/.vscode/launch.json
Labels: C++, NORMAL, 프로그래머스

#617 [Programmers Lv.1] 문자열 내 마음대로 정렬하기 (sort_arr_with_index)
  programmers/난이도별/level01.문자열_내_마음대로_정렬하기/develop-sell.js
Labels: JavaScript

#627 [level03] 단어변환, 자물쇠와 열쇠
  programmers/난이도별/level03.단어_변환/sangmandu.py
  programmers/난이도별/level03.자물쇠와열쇠/sangmandu.py
Labels: NORMAL, Python, 프로그래머스
