Repository DKU-STUDY/Algorithm, pull requests merged in 2020-06, with the labels that each got.

#170 일일 pr 입니다
  codility_training/lessons.lesson13.FibonacciNumbers.Ladder/JeongShin.js
Labels: JavaScript

#171 lessons.lesson10.PrimeAndCompositeNumbers.MinPerimeterRectangle
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.MinPerimeterRectangle/README.md
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.MinPerimeterRectangle/sjjyy.java
Labels: JAVA

#173 lessons.lesson09.MaximumSliceProblem.MaxDoubleSliceSum
  codility_training/lessons.lesson09.MaximumSliceProblem.MaxDoubleSliceSum/sjjyy.java
Labels: JAVA

#175 일일 pr 입니다
  codility_training/lessons.lesson14.BinarySearchAlgorithm.MinMaxDivision/JeongShin.js
Labels: JavaScript

#177 lessons.lesson05.PrefixSums.MinAvgTwoSlice
  codility_training/lessons.lesson05.PrefixSums.MinAvgTwoSlice/sjjyy.java
Labels: JAVA

#178 0603 일일 커밋입니다. #실패
  programmers/난이도별/level02.프린터/README.md
  programmers/난이도별/level02.프린터/dkdlelk99.py
Labels: Python

#179 lessons.lesson15.CaterpillarMethod.CountDistinctSlice
  codility_training/lessons.lesson14.BinarySearchAlgorithm.NailingPlanks/JeongShin.js
  codility_training/lessons.lesson15.CaterpillarMethod.AbsDistinct/JeongShin.js
  codility_training/lessons.lesson15.CaterpillarMethod.CountDistinctSlices/JeongShin.js
Labels: JavaScript

#180 lessons.lesson15.CaterpillarMethod.CountTriangles
  codility_training/lessons.lesson15.CaterpillarMethod.CountTriangles/JeongShin.js
Labels: JavaScript

#182 lessons.lesson04.CountingElements.MissingInteger
  codility_training/lessons.lesson04.CountingElements.MissingInteger/pul8219.java
Labels: JAVA

#183 lessons.lesson06.Sorting.NumberOfDiscIntersections
  codility_training/lessons.lesson06.Sorting.NumberOfDiscIntersections/sjjyy.java
Labels: JAVA

#186 lesson15.CaterpillarMethod.MinAbsSumOfTwo
  codility_training/lessons.lesson15.CaterpillarMethod.MinAbsSumOfTwo/JeongShin.js
Labels: JavaScript

#189 lessons.lesson16.GreedyAlgorithms.MaxNonOverLappingSegments
  codility_training/lessons.lesson16.GreedyAlgorithms.MaxNonOverLappingSegments/JeongShin.js
Labels: JavaScript

#190 0610 일일커밋입니다.
  programmers/난이도별/level01.문자열_내_마음대로_정렬하기/README.md
  programmers/난이도별/level01.문자열_내_마음대로_정렬하기/dkdlelk99.py
Labels: Python

#191 lessons.lesson17.DynamicProgramming.MinAbsSum
  codility_training/lessons.lesson16.GreedyAlgorithms.TieRopes/JeongShin.js
  codility_training/lessons.lesson17.DynamicProgramming.MinAbsSum/JeongShin.js
Labels: JavaScript

#192 0611 일일커밋입니다.
  programmers/난이도별/level01.모의고사/README.md
  programmers/난이도별/level01.모의고사/dkdlelk99.py
Labels: Python

#187 lessons.lesson10.PrimeAndCompositeNumbers.Peaks
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.Peaks/README.md
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.Peaks/sjjyy.java
Labels: JAVA

#193 0612 일일커밋입니다.
  programmers/난이도별/level01.체육복/README.md
  programmers/난이도별/level01.체육복/dkdlelk99.py
Labels: Python

#195 lesson90.TasksFromIndeedPrime2015Challenge.FloodDepth
  codility_training/lessons.lesson17.DynamicProgramming.MinAbsSum/JeongShin.js
  codility_training/lessons.lesson17.DynamicProgramming.NumberSolitaire/JeongShin.js
  codility_training/lessons.lesson90.TasksFromIndeedPrime2015Challenge.FloodDepth/JeongShin.js
  codility_training/lessons.lesson90.TasksFromIndeedPrime2015Challenge.LongestPassword/JeongShin.js
Labels: JavaScript

#194 lessons.lesson12.EuclideanAlgorithm.ChocolatesByNumbers
  codility_training/lessons.lesson12.EuclideanAlgorithm.ChocolatesByNumbers/README.md
  codility_training/lessons.lesson12.EuclideanAlgorithm.ChocolatesByNumbers/sjjyy.java
Labels: JAVA

#199 lessons.lesson90.TasksFromIndeedPrime2015Challenge.SlalomSkiing
  codility_training/lessons.lesson90.TasksFromIndeedPrime2015Challenge.SlalomSkiing/JeongShin.js
Labels: JavaScript

#198 lessons.lesson12.EuclideanAlgorithm.CommonPrimeDivisors
  codility_training/lessons.lesson05.PrefixSums.MinAvgTwoSlice/sjjyy.java
  codility_training/lessons.lesson06.Sorting.NumberOfDiscIntersections/sjjyy.java
  codility_training/lessons.lesson11.SieveofEratosthenes.CountNonDivisible/sjjyy.java
  codility_training/lessons.lesson11.SieveofEratosthenes.CountSemiprimes/READMD.md
  codility_training/lessons.lesson11.SieveofEratosthenes.CountSemiprimes/sjjyy.java
  codility_training/lessons.lesson12.EuclideanAlgorithm.ChocolatesByNumbers/sjjyy.java
  codility_training/lessons.lesson12.EuclideanAlgorithm.CommonPrimeDivisors/README.md
  codility_training/lessons.lesson12.EuclideanAlgorithm.CommonPrimeDivisors/sjjyy.java
Labels: JAVA

#200 0615일일 커밋입니다
  programmers/난이도별/level01.[1차]_비밀지도/README.md
  programmers/난이도별/level01.[1차]_비밀지도/dkdlelk99.py
Labels: Python

#202 lesson91.TaksFromIndeedPrime2016Challenge.DwarfsRafting
  codility_training/lessons.lesson90.TasksFromIndeedPrime2015Challenge.SlalomSkiing/JeongShin.js
  codility_training/lessons.lesson91.TaksFromIndeedPrime2016Challenge.DwarfsRafting/JeongShin.js
Labels: JavaScript

#204 TasksFromIndeedPrime2016Challenge.RectangleBuilderGreaterArea
  codility_training/lessons.lesson91.TaksFromIndeedPrime2016Challenge.DwarfsRafting/JeongShin.js
  codility_training/lessons.lesson91.TasksFromIndeedPrime2016Challenge.RectangleBuilderGreaterArea/JeongShin.js
Labels: JavaScript

#203 lessons.lesson11.SieveofEratosthenes.CountNonDivisible
  codility_training/lessons.lesson11.SieveofEratosthenes.CountNonDivisible/sjjyy.java
Labels: JAVA

#205 FutureTraining.StrSymmetryPoint/JeongShin.js
  codility_training/lessons.lesson91.TasksFromIndeedPrime2016Challenge.TreeProduct/JeongShin.js
  codility_training/lessons.lesson99.FutureTraining.StrSymmetryPoint/JeongShin.js
Labels: JavaScript

#207 lessons.lesson10.PrimeAndCompositeNumbers.MinPerimeterRectangle
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.MinPerimeterRectangle/README.md
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.MinPerimeterRectangle/eyabc.js
Labels: JavaScript

#208 lesson99.FutureTraining.ArrayInversionCount/JeongShin.js
  codility_training/lessons.lesson99.FutureTraining.ArrayInversionCount/JeongShin.js
Labels: JavaScript

#209 lessons.lesson13.FibonacciNumbers.Ladder
  codility_training/lessons.lesson10.PrimeAndCompositeNumbers.Peaks/sjjyy.java
  codility_training/lessons.lesson13.FibonacciNumbers.Ladder/README.md
  codility_training/lessons.lesson13.FibonacciNumbers.Ladder/sjjyy.java
Labels: JAVA

#210 lesson92.TaskFromIndeedPrime2016CollegeCodersChallenge.SocksLaundering
  codility_training/lessons.lesson92.TaskFromIndeedPrime2016CollegeCodersChallenge.SocksLaundering/JeongShin.js
Labels: JavaScript

#211 lessons.lesson99.FutureTraining.TreeHeight
  codility_training/lessons.lesson92.TasksFromIndeedPrime2016.CollegeCodersChallenge.DiamondsCount/JeongShin.js
  codility_training/lessons.lesson99.FutureTraining.TreeHeight/JeongShin.js
Labels: JavaScript

#212 level03.N_Queen
  programmers/난이도별/level03.N_Queen/JeongShin.js
Labels: JavaScript

#213 lessons.lesson11.SieveofEratosthenes.CountSemiprimes
  codility_training/lessons.lesson11.SieveofEratosthenes.CountSemiprimes/sjjyy.java
Labels: JAVA

#214 level03.정수삼각형
  programmers/난이도별/level03.정수삼각형/JeongShin.js
Labels: JavaScript

#216 level03.단속카메라
  programmers/난이도별/level03.단속카메라/JeongShin.js
Labels: JavaScript

#215 lessons.lesson13.FibonacciNumbers.FibFrog;
  codility_training/lessons.lesson13.FibonacciNumbers.FibFrog/README.md
  codility_training/lessons.lesson13.FibonacciNumbers.FibFrog/sjjyy.java
  codility_training/lessons.lesson15.CaterpillarMethod.AbsDistinct/README.md
  codility_training/lessons.lesson15.CaterpillarMethod.AbsDistinct/sjjyy.java
Labels: JAVA

#217 level03.단어_변환
  programmers/난이도별/level02.저울/JeongShin.js
  programmers/난이도별/level03.단어_변환/JeongShin.js
Labels: JavaScript

#218 lessons.lesson15.CaterpillarMethod.CountTriangles;
  codility_training/lessons.lesson15.CaterpillarMethod.CountTriangles/sjjyy.java
Labels: JAVA

#219 level03.섬_연결하기
  programmers/난이도별/level03.섬_연결하기/JeongShin.js
Labels: JavaScript

#201 0616 일일커밋입니다.
  programmers/난이도별/level01.소수찾기/dkdlelk99.py
  programmers/난이도별/level01.크레인_인형뽑기_게임/README.md
  programmers/난이도별/level01.크레인_인형뽑기_게임/dkdlelk99.py
Labels: Python
