Repository DKU-STUDY/Algorithm, pull requests merged in 2021-07, with the labels that each got.

#953 level03. 경주로 건설
  programmers/난이도별/level03.경주로_건설/rockmiin.py
Labels: Python, 프로그래머스

#955 [Level03] 모두 0으로 만들기, 하노이의 탑
  programmers/난이도별/level03.모두_0으로_만들기/sangmandu.py
  programmers/난이도별/level03.하노이의_탑/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#956 [level01] 약수의 개수와 덧셈
  programmers/난이도별/level01.약수의_개수와_덧셈/Go-yj.py
Labels: EASY, Python, 프로그래머스

#960 [level01] 3진법 뒤집기, 예산, 음양 더하기, 크레인 인형뽑기 게임
  programmers/난이도별/level01.3진법_뒤집기/Go-yj.py
  programmers/난이도별/level01.예산/Go-yj.py
  programmers/난이도별/level01.음양_더하기/Go-yj.py
  programmers/난이도별/level01.크레인_인형뽑기_게임/Go-yj.py
Labels: EASY, Python, 프로그래머스

#959 [Level03] 멀리뛰기
  programmers/난이도별/level03.멀리뛰기/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#964 [Level03] 합승 택시 요금
  programmers/난이도별/level03.합승_택시_요금/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#962 [level01] 내적, 모의고사, 신규 아이디 추천
  programmers/난이도별/level01.내적/Go-yj.py
  programmers/난이도별/level01.모의고사/Go-yj.py
  programmers/난이도별/level01.신규_아이디_추천/Go-yj.py
Labels: EASY, Python, 프로그래머스

#963 [programmers] 1단계 26개 / [programmers]베스트앨범 / [programmers]최고의집합 / [programmers]야근지수 / [programmers]N Queen
  programmers/난이도별/level01.3진법_뒤집기/6047198844.py
  programmers/난이도별/level01.[1차]_다트_게임/6047198844.py
  programmers/난이도별/level01.x만큼_간격이_있는_n개의_숫자/6047198844.py
  programmers/난이도별/level01.나누어_떨어지는_숫자_배열/6047198844.py
  programmers/난이도별/level01.동물의_아이디와_이름/6047198844.sql
  programmers/난이도별/level01.모든_레코드_조회하기/6047198844.sql
  programmers/난이도별/level01.문자열_내_p와_y의_개수/6047198844.py
  programmers/난이도별/level01.문자열_내_마음대로_정렬하기/6047198844.txt
  programmers/난이도별/level01.문자열_내림차순으로_배치하기/6047198844.py
  programmers/난이도별/level01.문자열을_정수로_바꾸기/6047198844.py
  programmers/난이도별/level01.상위_n개_레코드/6047198844.sql
  programmers/난이도별/level01.서울에서_김서방_찾기/6047198844.py
  programmers/난이도별/level01.수박수박수박수/6047198844.py
  programmers/난이도별/level01.시저_암호/6047198844.py
  programmers/난이도별/level01.아픈_동물_찾기/6047198844.sql
  programmers/난이도별/level01.약수의_합/6047198844.py
  programmers/난이도별/level01.어린_동물_찾기/6047198844.sql
  programmers/난이도별/level01.여러_기준으로_정렬하기/6047198844.sql
  programmers/난이도별/level01.역순_정렬하기/6047198844.sql
  programmers/난이도별/level01.예산/6047198844.py
  programmers/난이도별/level01.이름이_있는_동물의_아이디/6047198844.sql
  programmers/난이도별/level01.이상한_문자_만들기/6047198844.py
  programmers/난이도별/level01.자릿수_더하기/6047198844.py
  programmers/난이도별/level01.자연수_뒤집어_배열로_만들기/6047198844.py
  programmers/난이도별/level01.정수_내림차순으로_배치하기/6047198844.py
  programmers/난이도별/level01.정수_제곱근_판별/6047198844.py
  programmers/난이도별/level01.제일_작은_수_제거하기/6047198844.py
  programmers/난이도별/level01.직사각형_별찍기/6047198844.py
  programmers/난이도별/level01.짝수와_홀수/6047198844.py
  programmers/난이도별/level01.최대공약수와_최소공배수/6047198844.py
  programmers/난이도별/level01.콜라츠_추측/6047198844.py
  programmers/난이도별/level01.평균_구하기/6047198844.py
  programmers/난이도별/level01.하샤드_수/6047198844.py
  programmers/난이도별/level01.핸드폰_번호_가리기/6047198844.py
  programmers/난이도별/level01.행렬의_덧셈/6047198844.py
  programmers/난이도별/level03.N_Queen/6047198844.py
  programmers/난이도별/level03.베스트앨범/6047198844.py
  programmers/난이도별/level03.야근지수/6047198844.py
  programmers/난이도별/level03.최고의_집합/6047198844.py
Labels: 프로그래머스

#966 [level01]키패드 누르기, 소수 만들기
  programmers/난이도별/level01.키패드_누르기/Go-yj.py
  programmers/난이도별/level02.소수_만들기/Go-yj.py
Labels: EASY, Python, 프로그래머스

#967 [Level03] 징검다리 건너기
  programmers/난이도별/level03.징검다리_건너기/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#968 [level01] 로또의 최고 순위와 최저 순위, [level02] N개의 최소공배수
  programmers/난이도별/level01.로또의_최고_순위와_최저_순위/Go-yj.py
  programmers/난이도별/level02.N개의_최소공배수/Go-yj.py
Labels: EASY, Python, 프로그래머스

#970 [Level03] N-Queen
  programmers/난이도별/level03.N_Queen/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#971 [level02] JadenCase 문자열 만들기, 행렬의 곱셈
  programmers/난이도별/level02.JadenCase_문자열_만들기/Go-yj.py
  programmers/난이도별/level02.행렬의곱셈/Go-yj.py
Labels: EASY, Python, 프로그래머스

#972 [Level03] 표 편집, 불량 사용자
  programmers/난이도별/level03.불량_사용자/sangmandu.py
  programmers/난이도별/level03.표 편집/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#974 [BOJ] 연산자 끼워넣기 / [BOJ] 스타트와 링크
  BOJ/14888.연산자 끼워넣기/ms9849.cpp
  BOJ/14889. 스타트와 링크/ms9849.cpp
Labels: BOJ, C++, 완전탐색

#976 [Level01] 숫자 문자열과 영단어
  programmers/난이도별/level01.숫자_문자열과_영단어/sangmandu.py
Labels: EASY, Python, 프로그래머스

#978 [BOJ] 1로 만들기 2 / [BOJ] 정수 삼각형
  BOJ/12852.1로 만들기 2/ms9849.cpp
  BOJ/1932.정수 삼각형/ms9849.cpp
Labels: BOJ, C++, DP

#980 [Level02] 거리두기 확인하기
  programmers/난이도별/level02.거리두기_확인하기/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#981 [BOJ] 용액
  BOJ/2467.용액/ms9849.cpp
Labels: BOJ, C++

#975 [level02] 숫자의 표현, 최댓값과 최솟값, 최솟값 만들기, 피보나치 수
  programmers/난이도별/level02.숫자의_표현/Go-yj.py
  programmers/난이도별/level02.최댓값과_최솟값/Go-yj.py
  programmers/난이도별/level02.최솟값_만들기/Go-yj.py
  programmers/난이도별/level02.피보나치_수/Go-yj.py
Labels: EASY, Python, 프로그래머스

#983 [BOJ] 11051.이항 계수 2
  BOJ/11051.이항 계수 2/ms9849.cpp
Labels: BOJ, C++, DP

#982 [Level03] 단속카메라
  programmers/난이도별/level03.단속카메라/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#984 [level02] 땅따먹기
  programmers/난이도별/level02.땅따먹기/Go-yj.py
Labels: Python, 프로그래머스

#985 [BOJ] 1764. 듣보잡
  BOJ/1764. 듣보잡/ms9849.cpp
Labels: BOJ, C++

#988 [level02] [3차] n진수 게임, 다음 큰 숫자, 올바른 괄호
  programmers/난이도별/level02.n진수_게임/Go-yj.py
  programmers/난이도별/level02.다음_큰_숫자/Go-yj.py
  programmers/난이도별/level02.올바른_괄호/Go-yj.py
Labels: EASY, Python, 프로그래머스

#989 [BOJ] 7569.토마토
  BOJ/7569.토마토/ms9849.cpp
Labels: BOJ, C++

#986 [leetcode]ZigZag Conversion / Integer to Roman / Container With Most Water / 3Sum Closet / Pow(x,n) / Remove Nth Node From End of List / 4Sum / Generate Parentheses / Implement strStr() / Remove Duplicates from Sorted Array / [leetcode]Length of Last Word / [leetcode]Implement Trie (Prefix Tree)
  LeetCode/Array/3Sum_Closet/6047198844.py
  LeetCode/Array/4Sum/6047198844.py
  LeetCode/Array/Container_With_Most_Water/6047198844.py
  LeetCode/Array/Remove_Duplicates_from_Sorted_Array/6047198844.py
  LeetCode/Hash_Table/Implement_Trie_(Prefix_Tree)/6047198844.py
  LeetCode/Hash_Table/Integer_to_Roman/6047198844.py
  LeetCode/Linked_List/Remove_Nth_Node_From_End_of_List/6047198844.py
  LeetCode/Math/Pow(x,_n)/6047198844.py
  LeetCode/String/Generate_Parentheses/6047198844.py
  LeetCode/String/Implement_strStr()/6047198844.py
  LeetCode/String/Length_of_Last_Word/6047198844.py
  LeetCode/String/ZigZag_Conversion/6047198844.py
Labels: leetcode

#990 [Level03] 광고 제거
  programmers/난이도별/level01.실패율/sangmandu.py
  programmers/난이도별/level03.광고_제거/sangmandu.py
Labels: HARD, Python, 프로그래머스

#991 [level02] 파일명 정렬
  programmers/난이도별/level02.파일명_정렬/Go-yj.py
Labels: EASY, Python, 프로그래머스

#993 [Level03] 110 옮기기 [Level01] 폰켓몬, 소수 만들기
  programmers/난이도별/level01.소수_만들기/sangmandu.py
  programmers/난이도별/level01.자연수_뒤집어_배열로_만들기/sangmandu.py
  programmers/난이도별/level01.정수_내림차순으로_배치하기/sangmandu.py
  programmers/난이도별/level01.정수_제곱근_판별/sangmandu.py
  programmers/난이도별/level01.제일_작은_수_제거하기/sangmandu.py
  programmers/난이도별/level01.직사각혁_별찍기/sangmandu.py
  programmers/난이도별/level01.직사각형_별찍기/HyeonJeong.py
  programmers/난이도별/level01.직사각형_별찍기/README.md
  programmers/난이도별/level01.직사각형_별찍기/dkdlelk99.py
  programmers/난이도별/level01.직사각형_별찍기/sangmandu.py
  programmers/난이도별/level01.직사각형_별찍기/sjjyy.java
  programmers/난이도별/level01.짝수와_홀수/sangmandu.py
  programmers/난이도별/level01.체육복/sangmandu.py
  programmers/난이도별/level01.최대공약수와_최소공배수/sangmandu.py
  programmers/난이도별/level01.콜라츠_추측/sangmandu.py
  programmers/난이도별/level01.크레인_인형뽑기_게임/sangmandu.py
  programmers/난이도별/level01.키패드_누르기/6047198844.cpp
  programmers/난이도별/level01.키패드_누르기/sangmandu.py
  programmers/난이도별/level01.평균_구하기/sangmandu.py
  programmers/난이도별/level01.폰켓몬/sangmandu.py
  programmers/난이도별/level01.하샤드_수/sangmandu.py
  programmers/난이도별/level01.핸드폰_번호_가리기/sangmandu.py
  programmers/난이도별/level01.행렬의_덧셈/sangmandu.py
  programmers/난이도별/level03.110 옮기기/sangmandu.py
Labels: HARD, Python, 프로그래머스

#996 [Level03] 숫자 게임
  programmers/난이도별/level03.숫자_게임/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#997 [level01] 가장 큰 정사각형 찾기, 압축
  programmers/난이도별/level02.가장_큰_정사각형_찾기/Go-yj.py
  programmers/난이도별/level02.압축/Go-yj.py
Labels: EASY, Python, 프로그래머스

#998 [Level03] 줄 서는 방법, 기지국 설치
  programmers/난이도별/level02.124_나라의_숫자/sangmandu.py
  programmers/난이도별/level02.2개_이하로_다른_비트/sangmandu.py
  programmers/난이도별/level02.H-Index/sangmandu.py
  programmers/난이도별/level02.JadenCase_문자열_만들기/sangmandu.py
  programmers/난이도별/level02.N개의_최소공배수/6047198844.cpp
  programmers/난이도별/level02.N개의_최소공배수/sangmandu.py
  programmers/난이도별/level02.[3차]_방금_그곡/sangmandu.py
  programmers/난이도별/level02.[3차]_압축/sangmandu.py
  programmers/난이도별/level02.[3차]파일명_정렬/sangmandu.py
  programmers/난이도별/level02.가장_큰_수/sangmandu.py
  programmers/난이도별/level02.가장_큰_정사각형_찾기/sangmandu.py
  programmers/난이도별/level02.게임_맵_최단거리/sangmandu.py
  programmers/난이도별/level02.괄호_회전하기/sangmandu.py
  programmers/난이도별/level02.괄호변환/sangmandu.py
  programmers/난이도별/level02.구명보트/sangmandu.py
  programmers/난이도별/level02.기능개발/sangmandu.py
  programmers/난이도별/level02.뉴스_클러스터링/sangmandu.py
  programmers/난이도별/level02.다음_큰_숫자/sangmandu.py
  programmers/난이도별/level02.더_맵게/sangmandu.py
  programmers/난이도별/level02.땅따먹기/sangmandu.py
  programmers/난이도별/level02.멀쩡한_사각형/sangmandu.py
  programmers/난이도별/level02.메뉴_리뉴얼/rockmiin.py
  programmers/난이도별/level02.메뉴_리뉴얼/sangmandu.py
  programmers/난이도별/level02.문자열압축/sangmandu.py
  programmers/난이도별/level02.삼각_달팽이/sangmandu.py
  programmers/난이도별/level02.소수_만들기/sangmandu.py
  programmers/난이도별/level02.소수_찾기/sangmandu.py
  programmers/난이도별/level02.수식_최대화/sangmandu.py
  programmers/난이도별/level02.순위_검색/sangmandu.py
  programmers/난이도별/level02.숫자의_표현/sangmandu.py
  programmers/난이도별/level02/H_Index/6047198844.cpp
  programmers/난이도별/level02/JadenCase_문자열_만들기/6047198844.cpp
  programmers/난이도별/level02/숫자의_표현/6047198844.cpp
  programmers/난이도별/level03.기지국_설치/sangmandu.py
  programmers/난이도별/level03.줄_서는_방법/sangmandu.py
Labels: NORMAL, Python, 프로그래머스
