Repository DKU-STUDY/Algorithm, pull requests merged in 2021-06, with the labels that each got.

#833 [야근 지수]
  programmers/난이도별/level02.H-Index/khw970421.js
  programmers/난이도별/level03.야근_지수/khw970421.js
Labels: JavaScript, 코드리뷰, 프로그래머스

#797 소수찾기
  BOJ/1261.알고스팟/dosimpact.py
  BOJ/4195.친구네트워크/dosimpact.py
  programmers/난이도별/level01.소수찾기/dosimpact.py
  programmers/난이도별/level01.신규 아이디_추천/dosimpact.py
  programmers/난이도별/level01.실패율/HyeonJeong.py
  programmers/난이도별/level01.실패율/README.md
  programmers/난이도별/level01.실패율/dkdlelk99.py
  programmers/난이도별/level01.실패율/eyabc.js
  programmers/난이도별/level01.실패율/sangmandu.py
Labels: Math, 프로그래머스

#779 외발뛰기, 와일드 카드, 삼각형 위의 최대 경로
  알고스팟/삼각형 위의 최대 경로/삼각형 위의 최대 경로.py
  알고스팟/와일드카드/와일드카드.py
  알고스팟/외발뛰기/외발뛰기.py
Labels: DP, 알고스팟

#908 [Level02] 게임 맵 최단거리, 괄호 회전하기, 메뉴 리뉴얼 [LeetCode] Count Sorted Vowel Strings, Counting Bits
  LeetCode/DP/Count_Sorted_Vowel_Strings/sangmandu.py
  LeetCode/DP/Counting_Bits/sangmandu.py
  LeetCode/Greedy/Group_the_People_Given_the_Group_Size_They_Belong_To/sangmandu.py
  programmers/난이도별/level02.게임_맵_최단거리/sangmandu.py
  programmers/난이도별/level02.괄호_회전하기/sangmandu.py
  programmers/난이도별/level02.메뉴_리뉴얼/sangmandu.py
  programmers/난이도별/level02.순위_검색/sangmandu.py
Labels: DP, NORMAL, Python, leetcode, 프로그래머스

#911 [Level01] K번째수
  programmers/난이도별/level01.K번째수/Go-yj.py
Labels: EASY, Python, 프로그래머스

#913 [level01] x만큼 간격이 있는 n개의 숫자, 직사각형 별찍기
  programmers/난이도별/level01.x만큼_간격이_있는_n개의_숫자/Go-yj.py
  programmers/난이도별/level01.직사각혁_별찍기/Go-yj.py
Labels: EASY, Python, 프로그래머스

#916 [level01] 핸드폰 번호 가리기, 행렬의 덧셈
  programmers/난이도별/level01.핸드폰_번호_가리기/Go-yj.py
  programmers/난이도별/level01.행렬의_덧셈/Go-yj.py
Labels: EASY, Python, 프로그래머스

#917 [level01] 하샤드 수, 평균 구하기
  programmers/난이도별/level01.평균_구하기/Go-yj.py
  programmers/난이도별/level01.하샤드_수/Go-yj.py
Labels: EASY, Python, 프로그래머스

#910 [Level02] 2개 이하로 다른 비트, 행렬 테두리 회전하기, [LeetCode] Redundant Connection, Find Center of Star Graph
  LeetCode/Graph/Find_Center_of_Star_Graph/sangmandu.py
  LeetCode/Graph/Redundant_Connection/sangmandu.py
  programmers/난이도별/level02.2개_이하로_다른_비트/sangmandu.py
  programmers/난이도별/level02.행렬_테두리_회전하기/sangmandu.py
Labels: NORMAL, Python, leetcode, 프로그래머스

#918 [level01] 콜라츠 추측, 최대공약수와 최소공배수
  programmers/난이도별/level01.최대공약수와_최소공배수/Go-yj.py
  programmers/난이도별/level01.콜라츠_추측/Go-yj.py
Labels: EASY, Python, 프로그래머스

#920 [Level03] 입국심사
  programmers/난이도별/level03.가장_먼_노드/JeongShin.js
  programmers/난이도별/level03.가장_먼_노드/sangmandu.py
  programmers/난이도별/level03.가장_먼_노드/turquoiseluv.py
  programmers/난이도별/level03.입국심사/sangmandu.py
  programmers/난이도별/level03.정수_삼각형/6047198844.py
  programmers/난이도별/level03.정수_삼각형/JeongShin.js
  programmers/난이도별/level03.정수_삼각형/rockmiin.py
  programmers/난이도별/level03.정수_삼각형/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#923 [level01] 짝수와 홀수, 제일 작은 수 제거하기
  programmers/난이도별/level01.제일_작은_수_제거하기/Go-yj.py
  programmers/난이도별/level01.짝수와_홀수/Go-yj.py
Labels: EASY, Python, 프로그래머스

#924 [Level03] 디스크 컨트롤러
  programmers/난이도별/level03.디스크_컨트롤러/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#926 [Level03] 순위
  programmers/난이도별/level03.순위/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#922 [LeetCode] Reverse Integer
  LeetCode/Math/Reverse_Integer/SeokBin.java
Labels: EASY, JAVA, leetcode

#925 [level01] 정수 제곱근 판별, 정수 내림차순으로 배치하기
  programmers/난이도별/level01.정수_내림차순으로_배치하기/Go-yj.py
  programmers/난이도별/level01.정수_제곱근_판별/Go-yj.py
Labels: EASY, Python, 프로그래머스

#927 [Level03] 다단계 칫솔 판매, 불량 사용자
  programmers/난이도별/level03.다단계_칫솔_판매/sangmandu.py
  programmers/난이도별/level03.불량_사용자/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#906 [LeetCode] Group the People Given the Group Size They Belong To
  LeetCode/Greedy/Group_the_People_Given_the_Group_Size_They_Belong_To/HyeonJeong.py
Labels: Python, leetcode

#929 [level01] 자연수 뒤집어 배열로 만들기, 자릿수 더하기
  programmers/난이도별/level01.자릿수_더하기/Go-yj.py
  programmers/난이도별/level01.자연수_뒤집어_배열로_만들기/Go-yj.py
Labels: EASY, Python, 프로그래머스

#931 [level01] 이상한 문자 만들기
  programmers/난이도별/level01.이상한_문자_만들기/Go-yj.py
Labels: EASY, 프로그래머스

#930 [Level03] [1차] 셔틀버스
  programmers/난이도별/level03.[1차]_셔틀버스/sangmandu.py
  programmers/난이도별/level03.가사검색/README.md
  programmers/난이도별/level03.가사검색/junilhwang.js
  programmers/난이도별/level03.불량_사용자/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#933 [level01] 약수의 합, 시저 암호
  programmers/난이도별/level01.시저_암호/Go-yj.py
  programmers/난이도별/level01.약수의_합/Go-yj.py
Labels: EASY, Python, 프로그래머스

#936 [Level03] 보석 쇼핑
  programmers/난이도별/level03.보석_쇼핑/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#937 [level01] 수박수박수박수박수박수?, 소수 찾기, 문자열을 정수로 바꾸기
  programmers/난이도별/level01.문자열을_정수로_바꾸기/Go-yj.py
  programmers/난이도별/level01.소수찾기/Go-yj.py
  programmers/난이도별/level01.수박수박수박수/Go-yj.py
Labels: EASY, Python, 프로그래머스

#941 [level01] 서울에서 김서방 찾기, 문자열 다루기 기본
  programmers/난이도별/level01.문자열_다루기_기본/Go-yj.py
  programmers/난이도별/level01.서울에서_김서방_찾기/Go-yj.py
Labels: EASY, Python, 프로그래머스

#943 [level01] 문자열 내림차순으로 배치하기, 문자열 내 마음대로 정렬하기, 문자열 내 p와 y의 개수
  programmers/난이도별/level01.문자열_내_p와_y의_개수/Go-yj.py
  programmers/난이도별/level01.문자열_내_마음대로_정렬하기/Go-yj.py
  programmers/난이도별/level01.문자열_내림차순으로_배치하기/Go-yj.py
Labels: EASY, Python, 프로그래머스

#940 [Level03] 이중우선순위큐
  programmers/난이도별/level03.이중우선순위큐/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#942 [programmers]단어 변환 / [programmers]여행경로 / [programmers]거스름돈 / [programmers]두 정수사이의 합 / [programmers]모의고사
  programmers/난이도별/level01.두 정수 사이의 합/6047198844.py
  programmers/난이도별/level01.모의고사/6047198844.py
  programmers/난이도별/level03.거스름돈/6047198844.py
  programmers/난이도별/level03.단어_변환/6047198844.py
  programmers/난이도별/level03.등굣길/6047198844.py
  programmers/난이도별/level03.여행경로/6047198844.py
Labels: EASY, 프로그래머스

#945 [Level03] 섬 연결하기
  programmers/난이도별/level03.섬_연결하기/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#947 2110. 공유기 설치
  BOJ/2110 공유기 설치/rockmiin.py
Labels: BOJ, Python

#944 [level01] 두 정수 사이의 합, 다트 게임, 나누어 떨어지는 숫자 배열, 같은 숫자는 싫어
  programmers/난이도별/level01.같은_숫자는_싫어/Go-yj.py
  programmers/난이도별/level01.나누어_떨어지는_숫자_배열/Go-yj.py
  programmers/난이도별/level01.다트_게임/Go-yj.py
  programmers/난이도별/level01.두_정수_사이의_합/Go-yj.py
Labels: EASY, Python, 프로그래머스

#946 [Level03] 거스름돈
  programmers/난이도별/level03.거스름돈/sangmandu.py
Labels: NORMAL, Python, 프로그래머스

#950 [level01] 비밀지도, 가운데 글자 가져오기
  programmers/난이도별/level01.가운데_글자_가져오기/Go-yj.py
  programmers/난이도별/level01.비밀지도/Go-yj.py
Labels: EASY, Python, 프로그래머스

#954 [level01]두 개 뽑아서 더하기
  programmers/난이도별/level01.두_개_뽑아서_더하기/Go-yj.py
Labels: EASY, Python, 프로그래머스

#951 [Level03] 경주로 건설
  programmers/난이도별/level03.경주로_건설/sangmandu.py
Labels: NORMAL, Python, 도움요청, 프로그래머스

#952 [programmers]N으로 표현 / [programmers]가운데 글자 가져오기
  programmers/난이도별/level01.가운데_글자_가져오기/6047198844.py
  programmers/난이도별/level03.N으로_표현/6047198844.py
Labels: EASY, 프로그래머스
